<?php
$redirectText=
"/Cardiac_MRI_Ct_Unit/\thttps://imaging.sheba.co.il/השירות_לדימות_הלב_ומערכת_כלי_הדם
/Sheba_imaging_mambers/\thttps://imaging.sheba.co.il/מי_אנחנו_מכון_הדימות
/films_Fluoroscopy/\thttps://imaging.sheba.co.il/צילומים_ובדיקות_שיקוף_מכון_דימות
/Sheba_imaging_mambers/280.htm\thttps://www.sheba.co.il/גב_יעל_פלד
/Sheba_imaging_mambers/423.htm\thttps://imaging.sheba.co.il/תמר_סבן
/402/216.htm\thttps://www.sheba.co.il/דר_אורי_רימון
/Pediatric_Imaging/\thttps://imaging.sheba.co.il/היחידה_לדימות_בילדים
/Focused_Ultrasound/\thttps://imaging.sheba.co.il/השירות_לאולטרסאונד_ממוקד
/Thoracic_Imaging_Unit/\thttps://imaging.sheba.co.il/היחידה_לדימות_בית_החזה_והריאות
/Sheba_imaging_mambers/197.htm\thttps://imaging.sheba.co.il/צוות_הסיעוד_במכון_הדימות
/Pediatric_Imaging/Pediatric_US/\thttps://imaging.sheba.co.il/היחידה_לדימות_בילדים
/435/\thttps://imaging.sheba.co.il/בדיקת_דימות_תחת_הרדמה_ילדים
/Thoracic_Imaging_Unit/Thoracic_Xray/\thttps://imaging.sheba.co.il/צילומים_ושיקופים_של_בית_החזה_והריאות
/Thoracic_Imaging_Unit/Thoracic_CT/\thttps://imaging.sheba.co.il/CT_חזה_וריאות
/preparation/162.htm\thttps://imaging.sheba.co.il/בילדים_CT_הכנה_לבדיקה
/Pediatric_Imaging/214.htm\thttps://www.sheba.co.il/דר_ליסה_רביב-זילקה
/FQA/106.htm\thttps://imaging.sheba.co.il/קרינה_מייננת_בבדיקות_הדמיה
/Neuro_interventional_service/\thttps://imaging.sheba.co.il/השירות_לנוירורדיולוגיה_פולשנית
/Neuro_interventional_service/251.htm\thttps://imaging.sheba.co.il/טיפול_במלפורמציות_עורקיות_ורידיות_במוח
/Neuro_interventional_service/254.htm\thttps://imaging.sheba.co.il/טיפול_בפתולוגיות_וסקולריות_של_חוט_השדרה
/Neuro_interventional_service/343.htm\thttps://www.sheba.co.il/דר_מתי_בקון
/Oncologic_Imaging/\thttps://imaging.sheba.co.il/היחידה_לדימות_אונקולוגי
/Emergency_Medicine/293.htm\thttps://imaging.sheba.co.il/53983
/Uroradiology/Uroradiology_Doctors/379.htm\thttps://imaging.sheba.co.il/53736
/Uroradiology/Uroradiology_MRI/\thttps://imaging.sheba.co.il/כליות_ומערכת_השתן_MRI
/central_nervous_system/\thttps://imaging.sheba.co.il/היחידה_לדימות_המוח_ועמוד_השדרה
/central_nervous_system/Spine_MRI/\thttps://imaging.sheba.co.il/MRI_עמוד_שדרה
/Pediatric_Imaging/211.htm\thttps://www.sheba.co.il/דר_מיכל_סודק_בן-_נון
/Sheba_imaging_mambers/193.htm\thttps://www.sheba.co.il/פרופ_אלי_קונן
/Interventional_Radiology/302.htm\thttps://www.sheba.co.il/דר_אלכסנדר_גרניאק
/Pediatric_Imaging/CT_Children/\thttps://imaging.sheba.co.il/CT_ילדים
/MRI/\thttps://imaging.sheba.co.il/בדיקת_תהודה_מגנטית
/MRI/221.htm\thttps://imaging.sheba.co.il/השירות_לאולטרסאונד_ממוקד
/Musculoskeletal_Imaging/Musculoskeletal_MRI/231.htm\thttps://imaging.sheba.co.il/להערכת_הסחוס_המפרקי_MRI
/News/4.htm\thttps://imaging.sheba.co.il/54128
/central_nervous_system/Spine_CT/\thttps://imaging.sheba.co.il/עמוד_שדרה_CT
/US/\thttps://imaging.sheba.co.il/אולטרסאונד_מכון_הדימות
/US/240.htm\thttps://imaging.sheba.co.il/אולטרסאונד_אשכים
/Interventional_Radiology/236.htm\thttps://imaging.sheba.co.il/US_ביופסיה_בהנחיית
/Interventional_Radiology/233.htm\thttps://imaging.sheba.co.il/53948
/Pediatric_Imaging/MRI_Children/\thttps://imaging.sheba.co.il/בדיקת_MRI_בילדים
/US/345.htm\thttps://www.sheba.co.il/דר_ירוחם_קליינבאום
/central_nervous_system/Brain_MRI/\thttps://imaging.sheba.co.il/MRI_מוח
/MRI/169.htm\thttps://imaging.sheba.co.il/54033
/Research_and_Development/255.htm\thttps://www.sheba.co.il/דר_תמר_קושניר
/Research_and_Development/\thttps://imaging.sheba.co.il/יחידת_המחקר_והפיתוח_של_מכון_הדימות
/Research_and_Development/330.htm\thttps://imaging.sheba.co.il/הדמיה_וספקטרוסקופיה_של_תהליכים_מטבוליים
/Research_and_Development/326.htm\thttps://imaging.sheba.co.il/הדמייה_תיפקודית_של-המוח_בתהודה_מגנטית
/Sheba_imaging_mambers/299.htm\thttps://www.sheba.co.il/דר_יעל_ענבר
/414/\thttps://www.sheba.co.il/תנאי_שימוש_ותקנון_האתר
/410/\thttps://www.sheba.co.il/צור_קשר
/Research_and_Development/325.htm\thttps://imaging.sheba.co.il/מחקרים_בחיות_מעבדה
/Sheba_imaging_mambers/294.htm\thttps://imaging.sheba.co.il/אילת_צביון
/Pediatric_Imaging/213.htm\thttps://www.sheba.co.il/דר_יצחק_יעקובסון
/Thoracic_Imaging_Unit/Thoracic_Imaging_Unit_Doctors/265.htm\thttps://imaging.sheba.co.il/53980
/Thoracic_Imaging_Unit/Thoracic_Imaging_Unit_Doctors/301.htm\thttps://www.sheba.co.il/דר_אינסה_גרינברג-_וולף
/History_of_Imaging/\thttps://imaging.sheba.co.il/מדפי_ההיסטוריה_מכון_הדימות
/History_of_Imaging/276.htm\thttps://imaging.sheba.co.il/ההיסטוריה_של_האולטרסאונד
/Sheba_imaging_mambers/283.htm\thttps://imaging.sheba.co.il/מר_אריה_מוסקוביץ
/423/\thttps://imaging.sheba.co.il/שרות_חוות_דעת_שניה_מכון_הדימות
/central_nervous_system/288.htm\thttps://www.sheba.co.il/דר_חן_הופמן
/US/239.htm\thttps://imaging.sheba.co.il/אולטרסאונד_אורתופדי
/Pediatric_Imaging/Pediatric_Xray/\thttps://imaging.sheba.co.il/בדיקות_רנטגן_בילדים
/CT/\thttps://imaging.sheba.co.il/53872
/Interventional_Radiology/234.htm\thttps://imaging.sheba.co.il/CT_ניקוז_בהנחיית
/Musculoskeletal_Imaging/Musculoskeletal_CT/\thttps://imaging.sheba.co.il/מערכת_השלדֹ_CT
/Musculoskeletal_Imaging/Musculoskeletal_Interventional/201.htm\thttps://imaging.sheba.co.il/מפרקים_הסקרואליאקליים_CT
/Abdominal_Imaging/Abdominal_Imaging_CT/\thttps://imaging.sheba.co.il/בטן_ומערכת_העיכול_CTֹ
/FQA/175.htm\thttps://imaging.sheba.co.il/חומרי_ניגוד_המכילים_יוד_בבדיקות
/Abdominal_Imaging/\thttps://imaging.sheba.co.il/53832
/Abdominal_Imaging/virtual_colonoscopy/\thttps://imaging.sheba.co.il/בדיקת_קולונוסקופיה_וירטואלית
/Abdominal_Imaging/Abdominal_Imaging_MRI/184.htm\thttps://imaging.sheba.co.il/בדיקת_תהודה_מגנטית_באיברי_הבטן
/Abdominal_Imaging/Abdominal_Imaging_Doctors/\thttps://imaging.sheba.co.il/53832
/Abdominal_Imaging/Abdominal_Imaging_interventional_service/\thttps://imaging.sheba.co.il/ניקוז_של_כיס_המרה_ושל_דרכי_המרה
/Abdominal_Imaging/Abdominal_Imaging_Doctors/432.htm\thttps://imaging.sheba.co.il/54126
/Cardiac_MRI_Ct_Unit/Cardiac_MRI_Ct_Doctors/\thttps://imaging.sheba.co.il/53947
/Cardiac_MRI_Ct_Unit/Cardiac_MRI_Ct_Doctors/286.htm\thttps://www.sheba.co.il/דר_יעל_עשת
/Cardiac_MRI_Ct_Unit/215.htm\thttps://www.sheba.co.il/דר_אורלי_גויטיין
/films_Fluoroscopy/270.htm\thttps://imaging.sheba.co.il/ההיסטוריה_של_הרנטגן
/Uroradiology/\thttps://imaging.sheba.co.il/השירות_לדימות_הכליות_ומערכת_השתן
/Uroradiology/Uroradiology_interventional_service/\thttps://imaging.sheba.co.il/בדיקות_וטיפולים_פולשניים_כליות_ומערכת_השתן
/archive/\thttps://imaging.sheba.co.il/ארכיון_מכון_הדימות
/Sheba_imaging_mambers/334.htm\thttps://imaging.sheba.co.il/שמרית_סקופ
/Musculoskeletal_Imaging/Musculoskeletal_MRI/\thttps://imaging.sheba.co.il/מערכת_השלד_MRI
/US/103.htm\thttps://imaging.sheba.co.il/אולטרסאונד_צוואר
/Abdominal_Imaging/Abdominal_Imaging_XRay/\thttps://imaging.sheba.co.il/רנטגן_ובדיקות_שיקוף_בטן_ומערכת_העיכול
/Abdominal_Imaging/Abdominal_Imaging_XRay/112.htm\thttps://imaging.sheba.co.il/בדיקת_מעבר_מעי_דק
/Abdominal_Imaging/Abdominal_Imaging_XRay/111.htm\thttps://imaging.sheba.co.il/בדיקת_שיקוף_ושט-קיבה-תריסריון
/central_nervous_system/central_nervous_system_Doctors/337.htm\thttps://www.sheba.co.il/דר_מאיר_פייבל
/Research_and_Development/331.htm\thttps://imaging.sheba.co.il/דימות_מחקר_ופיתוח_מדידת_טמפ_במוח_סכיזופרן
/History_of_Imaging/277.htm\thttps://imaging.sheba.co.il/ההיסטוריה_של_הטומוגרפיה_הממוחשבת
/History_of_Imaging/318.htm\thttps://imaging.sheba.co.il/ההיסטוריה_של_הטומוגרפיה_הממוחשבת
/central_nervous_system/central_nervous_system_Doctors/\thttps://imaging.sheba.co.il/54004
/central_nervous_system/central_nervous_system_Doctors/335.htm\thttps://www.sheba.co.il/דר_גל_גרינברג
/450/\thttps://imaging.sheba.co.il/אולטראסאונד_ודופלר_של_כלי_הדם
/Interventional_Radiology/235.htm\thttps://imaging.sheba.co.il/US_ניקוז_בהנחיית
/preparation/209.htm\thttps://imaging.sheba.co.il/הכנה_לפני_ביצוע_ביופסיה
/Breast_Imaging_Unit/Breast_MRI/\thttps://imaging.sheba.co.il/שד_MRI
/Musculoskeletal_Imaging/\thttps://imaging.sheba.co.il/53827
/Musculoskeletal_Imaging/Musculoskeletal_XRay/\thttps://imaging.sheba.co.il/צילומי_רנטגן_מערכת_השלד
/Neuro_interventional_service/252.htm\thttps://imaging.sheba.co.il/טיפול_בשבץ_מוחי
/Uroradiology/Uroradiology_Doctors/\thttps://imaging.sheba.co.il/53855
/Cardiac_MRI_Ct_Unit/CTA/\thttps://imaging.sheba.co.il/בדיקת_סיטי_כל_דם
/Cardiac_MRI_Ct_Unit/Cardiac_MRI_Ct_Doctors/272.htm\thttps://www.sheba.co.il/פרופ_אליו_די_סגני
/CT/364.htm\thttps://www.sheba.co.il/54068
/US/238.htm\thttps://imaging.sheba.co.il/כליות_ומערכת_השתן_US
/Thoracic_Imaging_Unit/Thoracic_MRI/\thttps://imaging.sheba.co.il/MRI_בית_החזה_וריאות
/Musculoskeletal_Imaging/Musculoskeletal_Imaging_Doctors/\thttps://imaging.sheba.co.il/53827
/Breast_Imaging_Unit/\thttps://imaging.sheba.co.il/היחידה_לדימות_השד
/Breast_Imaging_Unit/194.htm\thttps://www.sheba.co.il/דר_אריה_רונדשטין
/Breast_Imaging_Unit/screening_diagnosis/\thttps://imaging.sheba.co.il/בדיקות_פולשניות_של_השד
/Breast_Imaging_Unit/Breast_US/\thttps://imaging.sheba.co.il/שד_US
/Neuro_interventional_service/253.htm\thttps://imaging.sheba.co.il/טיפול_ודה_וסקולריזציה_של_גידולים
/365/\thttps://imaging.sheba.co.il/סי.טי_של_מערכת_המין_והרבייה
/Cardiac_MRI_Ct_Unit/Cardiac_CT_Angiography/\thttps://imaging.sheba.co.il/ֹלב_CT_בדיקת
/Cardiac_MRI_Ct_Unit/Cardiac_CT_Angiography/324.htm\thttps://imaging.sheba.co.il/53831
/FQA/\thttps://imaging.sheba.co.il/שאלות_נפוצות_בהדמיה
/FQA/202.htm\thttps://imaging.sheba.co.il/למי_אסור_להיבדק_במכשיר_אמ_אר_איי
/FQA/237.htm\thttps://imaging.sheba.co.il/מועד_הגעת_תשובות_מדימות
/FQA/203.htm\thttps://imaging.sheba.co.il/בדיקות_דימות_במהלך_הריון
/473/\thttps://imaging.sheba.co.il/הערמונית_MRI
/Uroradiology/Uroradiology_XRay/\thttps://imaging.sheba.co.il/רנטגן_ושיקופים_לדימות_הכליות_ומערכת_השתן
/Uroradiology/Uroradiology_XRay/126.htm\thttps://imaging.sheba.co.il/בדיקת_ציסטוגרפיה
/Uroradiology/Uroradiology_XRay/125.htm\thttps://imaging.sheba.co.il/IVP_בדיקת
/Cardiac_MRI_Ct_Unit/MRA/\thttps://imaging.sheba.co.il/MRA_כלי_הדם
/Cardiac_MRI_Ct_Unit/MRA/157.htm\thttps://imaging.sheba.co.il/53869
/central_nervous_system/CT_Brain/\thttps://imaging.sheba.co.il/CT_בדיקת__ראש_מוח
/ct/364.htm\thttps://www.sheba.co.il/54068
/Pediatric_Imaging/212.htm\thttps://www.sheba.co.il/דר_אביבה_בן-שלוש
/central_nervous_system/291.htm\thttps://www.sheba.co.il/דר_חן_הופמן
/preparation/167.htm\thttps://imaging.sheba.co.il/בילדים_CT_הכנה_לבדיקה
/FQA/271.htm\thttps://imaging.sheba.co.il/Nephrogenic_Systemic_fibrosis
/Mamography/\thttps://imaging.sheba.co.il/53787
/Cardiac_MRI_Ct_Unit/Cardiac_MRI/\thttps://imaging.sheba.co.il/MRI_של_הלב
/Abdominal_Imaging/Abdominal_Imaging_XRay/110.htm\thttps://imaging.sheba.co.il/בדיקת_חוקן_בריום
/Uroradiology/Uroradiology_CT/\thttps://imaging.sheba.co.il/כליות_ומערכת_השתן_CT
/Research_and_Development/323.htm\thttps://imaging.sheba.co.il/מקורות_בבליוגרפים_למחקרים_מערכת-הראייה
/Interventional_Radiology/208.htm\thttps://www.sheba.co.il/דר_גיל_גולן
/Musculoskeletal_Imaging/Musculoskeletal_US/\thttps://imaging.sheba.co.il/אורתופדי_US
/Emergency_Medicine/\thttps://imaging.sheba.co.il/השירות_לדימות_רפואה_דחופה_וטראומה
/402/\thttps://www.sheba.co.il/דר_אורי_רימון
/News/\thttps://www.sheba.co.il/חדשות
/449/\thttps://imaging.sheba.co.il/54021
/Abdominal_Imaging/Abdominal_Imaging_US/\thttps://imaging.sheba.co.il/בטן_US
/Abdominal_Imaging/Abdominal_Imaging_Doctors/217.htm\thttps://www.sheba.co.il/דר_מיכל_אמיתי
/347/\thttps://imaging.sheba.co.il/כלי_דם_רדיולוגיה_פולשנית
/Interventional_Radiology/135.htm\thttps://imaging.sheba.co.il/הכנסת_צנתרים_מרכזיים
/Interventional_Radiology/87.htm\thttps://imaging.sheba.co.il/טיפול_בהיצרויות_ובחסימות_של-כלי_דם
/Interventional_Radiology/127.htm\thttps://imaging.sheba.co.il/טיפול_בדימומים
/Interventional_Radiology/132.htm\thttps://imaging.sheba.co.il/טיפול_בחולי_דיאליזה_דימות
/Interventional_Radiology/130.htm\thttps://imaging.sheba.co.il/טיפול_במלפורמציות_וסקולריות
/Interventional_Radiology/133.htm\thttps://imaging.sheba.co.il/53846
/FQA/204.htm\thttps://imaging.sheba.co.il/בדיקת_אמ_אר_איי_קלסטרופובים
/Breast_Imaging_Unit/Breast_Imaging_Mamography/\thttps://imaging.sheba.co.il/53787
/History_of_Imaging/278.htm\thttps://imaging.sheba.co.il/ההיסטוריה_של_התהודה_המגנטית
/360/\thttps://imaging.sheba.co.il/ממוגרפיה_שד
/Abdominal_Imaging/Abdominal_Imaging_MRI/\thttps://imaging.sheba.co.il/בדיקת_תהודה_מגנטית_באיברי_הבטן
/central_nervous_system/myelography/\thttps://imaging.sheba.co.il/מכון_הדימות_CT_מיאלוגרפיה
/preparation/\thttps://imaging.sheba.co.il/הכנה_לבדיקות_דימות
/preparation/166.htm\thttps://imaging.sheba.co.il/של_המח_בית_החזה_והצוואר_CT_הכנה_לבדיקת
/preparation/159.htm\thttps://imaging.sheba.co.il/אורוגרפיה_CT_הכנה_לביצוע_בדיקת
/preparation/161.htm\thttps://imaging.sheba.co.il/ארתרוגרפיה_MRI_הכנה_לבדיקת
/preparation/160.htm\thttps://imaging.sheba.co.il/ארתרוגרפיה_CT_הכנה_לבדיקת
/preparation/165.htm\thttps://imaging.sheba.co.il/הכנה_לבדיקת_סיטי_גוף
/preparation/158.htm\thttps://imaging.sheba.co.il/בהרדמה_כללית_MRI_הכנה_לקראת_ביצוע
/preparation/164.htm\thttps://imaging.sheba.co.il/ֹאנגיוגרפיה_CT_הכנה_לבדיקת
/Interventional_Radiology/134.htm\thttps://imaging.sheba.co.il/הכנסת_פילטר_לוריד_הנבוב_התחתון
/News/&&adv_search=1\thttps://imaging.sheba.co.il/חדשות_מכון_הדימות
/Thoracic_Imaging_Unit/Thoracic_Imaging_Unit_Doctors/\thttps://imaging.sheba.co.il/53980
/preparation/281.htm\thttps://imaging.sheba.co.il/בהרדמה_CT_הכנות_לפני_בדיקת
/Interventional_Radiology/131.htm\thttps://imaging.sheba.co.il/טיפול_במפרצות_בכלי_הדם
/Pediatric_Imaging/Pediatric_Fluoroscopy/\thttps://imaging.sheba.co.il/בדיקות_שיקוף_בילדים
/Pediatric_Imaging/MRI_Children/189.htm\thttps://imaging.sheba.co.il/באבחון_טרום_מילדותי_MRI
/Pediatric_Imaging/MRI_Children/426.htm\thttps://www.sheba.co.il/דר_אלדד_קטורזה
/central_nervous_system/central_nervous_system_Doctors/300.htm\thttps://www.sheba.co.il/דר_גליה_צרפתי
/anesthetization/\thttps://imaging.sheba.co.il/בדיקות_דימות_תחת_הרדמה
/Uroradiology/Uroradiology_US/\thttps://imaging.sheba.co.il/כליות_ומערכת_השתן_US
/preparation/163.htm\thttps://imaging.sheba.co.il/לאבני_כליות_CT_הכנה_לבדיקת
/Neuro_interventional_service/249.htm\thttps://imaging.sheba.co.il/בדיקת_צנתור_של_המוח
/Interventional_Radiology/179.htm\thttps://imaging.sheba.co.il/טיפול_אנדווסקולרי_ביתר_לחץ_דם
/Neuro_interventional_service/250.htm\thttps://imaging.sheba.co.il/טיפול_במפרצת_מוחית
/Interventional_Radiology/128.htm\thttps://imaging.sheba.co.il/טיפול-_אנדווסקולרי_בחולים_אונקולוגיים
/Sheba_Sites/\thttps://research.sheba.co.il/42496
/Musculoskeletal_Imaging/Musculoskeletal_Interventional/\thttps://imaging.sheba.co.il/בדיקות_וטיפולים_פולשניים_מערכת_השלד
/Musculoskeletal_Imaging/Musculoskeletal_Interventional/198.htm\thttps://imaging.sheba.co.il/ארתרוגרפיה_CT
/Musculoskeletal_Imaging/Musculoskeletal_Interventional/199.htm\thttps://imaging.sheba.co.il/ארתרוגרפיה_MRI
/US/94.htm\thttps://imaging.sheba.co.il/בטן_US
/Interventional_Radiology/\thttps://imaging.sheba.co.il/רדיולוגיה_פולשנית
/Interventional_Radiology/358.htm\thttps://imaging.sheba.co.il/דף_מידע_למטופל
/Abdominal_Imaging/Abdominal_Imaging_interventional_service/141.htm\thttps://imaging.sheba.co.il/ניקוז_של_כיס_המרה_ושל_דרכי_המרה
/Interventional_Radiology/232.htm\thttps://imaging.sheba.co.il/item/57328/1/71882
/Interventional_Radiology/178.htm\thttps://imaging.sheba.co.il/item/57328/1/71882
/Interventional_Radiology/129.htm\thttps://imaging.sheba.co.il/טיפול_אנדווסקולרי_בשרירנים_רחמיים
/Interventional_Radiology/332.htm\thttps://imaging.sheba.co.il/דימות_רדיו_פולשנית_השמדת_גידולים_בגלי_רדיו
/History_of_Imaging/298.htm\thttps://imaging.sheba.co.il/היסטוריה_מכון_הדימות_שיבא
/History_of_Imaging/297.htm\thttps://imaging.sheba.co.il/54010
/History_of_Imaging/424.htm\thttps://imaging.sheba.co.il/תמונות_מהווי_מכון_הדימות
/History_of_Imaging/311.htm\thttps://imaging.sheba.co.il/תולדות_המכון_מפי_יצחק_נש";
?>