<?php
$redirectText=
"/545/\thttps://www.sheba.co.il/%D7%A4%D7%A8%D7%A1%D7%95%D7%9D_%D7%91%D7%90%D7%AA%D7%A8
/566/\thttps://yeladim.sheba.co.il/%D7%98%D7%9C%D7%A4%D7%95%D7%A0%D7%99%D7%9D-%D7%A1%D7%A4%D7%A8%D7%90
/573/\thttps://yeladim.sheba.co.il/%D7%98%D7%9C%D7%A4%D7%95%D7%A0%D7%99%D7%9D-%D7%A1%D7%A4%D7%A8%D7%90
/576/\thttps://yeladim.sheba.co.il/עמותות
/591/\thttps://yeladim.sheba.co.il/מילון-מושגים-בסיסיים
/606/\thttps://yeladim.sheba.co.il/פטרת_הקרקפת
/654/\thttps://yeladim.sheba.co.il/מרפאת-גסטרוסטום
/676/562.htm\thttps://yeladim.sheba.co.il/המרכז-למחקרים-קליניים
/article/\thttps://yeladim.sheba.co.il/סקירת_מחקרים_במכון_להתפתחות_הילד
/article/382.htm\thttps://yeladim.sheba.co.il/סקירת_מחקרים_במכון_להתפתחות_הילד
/article/384.htm\thttps://yeladim.sheba.co.il/פרסומים_מצגות_חוברת_תקצירים
/article/406.htm\thttps://yeladim.sheba.co.il/דרכים_לתת
/article/Articles_Library/\thttps://yeladim.sheba.co.il/מאמרים
/article/Articles_Library/118.htm\thttps://yeladim.sheba.co.il/כתבה_הנקת_תינוקות
/article/Articles_Library/119.htm\thttps://yeladim.sheba.co.il/כתבה_עיסוי_תינוקות
/article/Articles_Library/121.htm\thttps://yeladim.sheba.co.il/כתבה_הפעלת_תינוק_באמבטיה
/article/Articles_Library/122.htm\thttps://yeladim.sheba.co.il/כתבה_תינוק_בא_הביתה_בעיות_שכיחות
/article/Articles_Library/123.htm\thttps://yeladim.sheba.co.il/צעצועים_התפתחותיים
/article/Articles_Library/127.htm\thttps://yeladim.sheba.co.il/בריאות_שיני_התינוק
/article/Articles_Library/128.htm\thttps://yeladim.sheba.co.il/כתבה_בעיות_שינה_התנהגותיות
/article/Articles_Library/129.htm\thttps://yeladim.sheba.co.il/פרכוסי_חום
/article/Articles_Library/144.htm\thttps://yeladim.sheba.co.il/כתבה_אי_סבילות_לקטוז_ילדים
/article/Articles_Library/199.htm\thttps://yeladim.sheba.co.il/כתבה_השמנת-יתר_ילדים
/article/Articles_Library/205.htm\thttps://yeladim.sheba.co.il/כתבה_ברית_מילה_בשנות2000
/article/Articles_Library/212.htm\thttps://yeladim.sheba.co.il/כתבה_תרפיה_בתנועה
/article/Articles_Library/213.htm\thttps://yeladim.sheba.co.il/כתבה_טרשת_נפוצה_ילדים
/article/Articles_Library/215.htm\thttps://yeladim.sheba.co.il/כתבה_גמילה_מטיטולים
/article/Articles_Library/227.htm\thttps://yeladim.sheba.co.il/כתבה_לצאת_מהלחץ_ילדים
/article/Articles_Library/243.htm\thttps://yeladim.sheba.co.il/כתבה_פה_גדול
/article/Articles_Library/251.htm\thttps://yeladim.sheba.co.il/סדנאות_לטיפול_בהשמנת_יתר
/article/Articles_Library/268.htm\thttps://yeladim.sheba.co.il/כתבה_אמא_אני_מפחד
/article/Articles_Library/274.htm\thttps://yeladim.sheba.co.il/כתבה_הכיני_ילדך_לחורף
/article/Articles_Library/292.htm\thttps://yeladim.sheba.co.il/כתבה_הקשר_בין_אביב_לאלרגיה
/article/Articles_Library/293.htm\thttps://yeladim.sheba.co.il/כתבה_ארגון_סביבת_עבודה_לילד
/article/Articles_Library/300.htm\thttps://yeladim.sheba.co.il/כתבה_מומחים_משיבים_התפתחות_בילד
/article/Articles_Library/302.htm\thttps://yeladim.sheba.co.il/מאמרים
/article/Articles_Library/309.htm\thttps://yeladim.sheba.co.il/כתבה_שנת_תינוקות
/article/Articles_Library/310.htm\thttps://yeladim.sheba.co.il/אורח_חיים_בריא_הוא_רפואה_לכל_דבר
/article/Articles_Library/322.htm\thttps://yeladim.sheba.co.il/כתבה_להתמודד_עם_מחלות_בחורף
/article/Articles_Library/323.htm\thttps://yeladim.sheba.co.il/כתבה_חיסונים_ילדים
/article/Kidneys_and_urinary_path/\thttps://yeladim.sheba.co.il/כליות_ודרכי_השתן
/clinics/\thttps://yeladim.sheba.co.il/%D7%9E%D7%A8%D7%A4%D7%90%D7%95%D7%AA-%D7%99%D7%9C%D7%93%D7%99%D7%9D
/clinics/495.htm\thttps://yeladim.sheba.co.il/שירות_סוציאלי_המכון_להתפתחות_הילד
/clinics/A_T_national_clinic/\thttps://yeladim.sheba.co.il/AT_מרפאה_ארצית_לטיפול_בחולי
/clinics/A_T_national_clinic/488.htm\thttps://yeladim.sheba.co.il/AT_מרפאה_ארצית_לטיפול_בחולי
/clinics/Adolescent_clinic/\thttps://yeladim.sheba.co.il/מרפאת_מתבגרים
/clinics/allergy_clinic/\thttps://yeladim.sheba.co.il/מרפאת_אלרגיה_ילדים
/clinics/Cardiology_Clinic/\thttps://yeladim.sheba.co.il/מרפאת_קרדיולוגית_ילדים
/clinics/Child_Development_Institute/\thttps://yeladim.sheba.co.il/המכון_להתפתחות_הילד
/clinics/Child_Development_Institute/284.htm\thttps://yeladim.sheba.co.il/%D7%9E%D7%A8%D7%A4%D7%90%D7%95%D7%AA_%D7%94%D7%9E%D7%9B%D7%95%D7%9F_%D7%9C%D7%94%D7%AA%D7%A4%D7%AA%D7%97%D7%95%D7%AA_%D7%94%D7%99%D7%9C%D7%93
/clinics/Child_Development_Institute/285.htm\thttps://yeladim.sheba.co.il/%D7%9E%D7%A1%D7%92%D7%A8%D7%95%D7%AA_%D7%97%D7%99%D7%A0%D7%95%D7%9B%D7%99%D7%95%D7%AA_%D7%98%D7%99%D7%A4%D7%95%D7%9C%D7%99%D7%95%D7%AA
/clinics/Child_Development_Institute/289.htm\thttps://yeladim.sheba.co.il/%D7%AA%D7%97%D7%95%D7%9E%D7%99_%D7%9E%D7%97%D7%A7%D7%A8_%D7%91%D7%9E%D7%9B%D7%95%D7%9F_%D7%9C%D7%94%D7%AA%D7%A4%D7%AA%D7%97%D7%95%D7%AA_%D7%94%D7%99%D7%9C%D7%93
/clinics/Child_Development_Institute/518.htm\thttps://www.sheba.co.il/%D7%93%D7%A8%D7%95%D7%A9%D7%99%D7%9D_%D7%91%D7%A9%D7%99%D7%91%D7%90
/clinics/Child_Development_Institute/540.htm\thttps://yeladim.sheba.co.il/מוכנות_לכיתה_א
/clinics/Child_Development_Institute/541.htm\thttps://yeladim.sheba.co.il/השימוש_בטאבלט_עם_פעוטות_וילדים
/clinics/Child_Development_Institute/542.htm\thttps://yeladim.sheba.co.il/דף_מידע_להורים_מוטוריקה
/clinics/Child_Development_Institute/543.htm\thttps://yeladim.sheba.co.il/דף_מידע_להורים_גרפומוטוריקה
/clinics/Child_Development_Institute/544.htm\thttps://yeladim.sheba.co.il/מידע_להורים_הפרעה_התפתחותית_בקואורדינציה
/clinics/Child_Development_Institute/545.htm\thttps://yeladim.sheba.co.il/מידע_להורים_תקשורת_תומכת_חליפית
/clinics/Child_Development_Institute/546.htm\thttps://yeladim.sheba.co.il/%D7%9E%D7%9B%D7%95%D7%9F_%D7%9C%D7%94%D7%AA%D7%A4%D7%AA%D7%97%D7%95%D7%AA_%D7%94%D7%99%D7%9C%D7%93_%D7%9E%D7%99%D7%93%D7%A2_%D7%9C%D7%94%D7%95%D7%A8%D7%99%D7%9D
/clinics/Child_Development_Institute/552.htm\thttps://yeladim.sheba.co.il/פעילות_צוותים_פרה_רפואיים
/clinics/Child_Development_Institute/555.htm\thttps://yeladim.sheba.co.il/צהרונים
/clinics/Child_Development_Institute/68.htm\thttps://yeladim.sheba.co.il/%D7%94%D7%AA%D7%A4%D7%AA%D7%97%D7%95%D7%99%D7%95%D7%AA_%D7%A2%D7%99%D7%AA%D7%95%D7%9F_%D7%94%D7%9E%D7%A8%D7%9B%D7%96_%D7%9C%D7%94%D7%AA%D7%A4%D7%AA%D7%97%D7%95%D7%AA_%D7%94%D7%99%D7%9C%D7%93
/clinics/Child_Development_Institute/69.htm\thttps://yeladim.sheba.co.il/%D7%94%D7%AA%D7%A4%D7%AA%D7%97%D7%95%D7%99%D7%95%D7%AA_%D7%A2%D7%99%D7%AA%D7%95%D7%9F_%D7%94%D7%9E%D7%A8%D7%9B%D7%96_%D7%9C%D7%94%D7%AA%D7%A4%D7%AA%D7%97%D7%95%D7%AA_%D7%94%D7%99%D7%9C%D7%93
/clinics/Children_North/\thttps://yeladim.sheba.co.il/%D7%9E%D7%97%D7%9C%D7%A7%D7%AA_%D7%99%D7%9C%D7%93%D7%99%D7%9D_%D7%90_%D7%A6%D7%A4%D7%95%D7%9F
/clinics/Children_Rehabilitation/\thttps://yeladim.sheba.co.il/שיקום_ילדים
/clinics/Children_South/\thttps://yeladim.sheba.co.il/%D7%99%D7%9C%D7%93%D7%99%D7%9D_%D7%91_%D7%93%D7%A8%D7%95%D7%9D
/clinics/Coagulation_disorders_clinic/\thttps://yeladim.sheba.co.il/מרפאה_להפרעות_קרישה
/clinics/Dental_clinic/\thttps://yeladim.sheba.co.il/מרפאת_שיניים_לילדים
/clinics/eating_disorder_clinic/\thttps://yeladim.sheba.co.il/המרפאה_להפרעות_אכילה_לילדים_ונוער
/clinics/Endocrinology_Clinic_juvenile_diabetes/\thttps://yeladim.sheba.co.il/סוכרת_נעורים
/clinics/Endocrinology_Clinic_juvenile_diabetes/176.htm\thttps://yeladim.sheba.co.il/קומה_נמוכה
/clinics/Endocrinology_Clinic_juvenile_diabetes/179.htm\thttps://yeladim.sheba.co.il/דפי_מידע_סוכרת_נעורים
/clinics/Eye_clinic/\thttps://yeladim.sheba.co.il/מרפאת_עיניים_לילדים
/clinics/Gaster_Clinic/\thttps://yeladim.sheba.co.il/היחידה_לגסטרואנטרולוגיה_לילדים
/clinics/Gaster_Clinic/193.htm\thttps://yeladim.sheba.co.il/מרפאת-גסטרוסטום
/clinics/Gaster_Clinic/291.htm\thttps://yeladim.sheba.co.il/מרפאה_לבעיות_אכילה_בליעה_ושגשוג_בילדים_בגיל_הרך
/clinics/Gaster_Clinic/336.htm\thttps://yeladim.sheba.co.il/עצירות
/clinics/Gaster_Clinic/476.htm\thttps://yeladim.sheba.co.il/מרפאה_תסמונת_המעי_הקצר_ילדים
/clinics/heart_defects_clinic/\thttps://yeladim.sheba.co.il/המרפאה_לאלקטרופיזיולוגיה_בילדים_ובמומי_לב_מולדים
/clinics/heart_defects_clinic/ECMO\thttps://yeladim.sheba.co.il/חימצון_חוץ_גופי_אקמו
/clinics/Hmtoaonkology/\thttps://yeladim.sheba.co.il/המטו-אונקולוגיה_ילדים
/clinics/Hmtoaonkology/Department_of_hospitalization/\thttps://yeladim.sheba.co.il/מחלקת_האישפוז
/clinics/Hmtoaonkology/Institute_Hhmto___Oncology/\thttps://yeladim.sheba.co.il/המכון_ההמטו-אונקולוגי
/clinics/Hmtoaonkology/Institute_Hhmto___Oncology/Beit_Wiesel/\thttps://yeladim.sheba.co.il/משכן_מריון_ואלי_ויזל
/clinics/Hmtoaonkology/Institute_Hhmto___Oncology/Contact_Us/\thttps://yeladim.sheba.co.il/צור_קשר
/clinics/Imaging_unit/\thttps://yeladim.sheba.co.il/דפי_מידע_דימות_ילדים
/clinics/Imaging_unit/112.htm\thttps://yeladim.sheba.co.il/הכנה_לבדיקת_MRI
/clinics/Immunology_clinic/\thttps://yeladim.sheba.co.il/מרפאת_אימונולוגיה_ילדים
/clinics/Infectious_diseases_clinic/\thttps://yeladim.sheba.co.il/מרפאה_למחלות_זיהומיות
/clinics/Intensive_Care/\thttps://yeladim.sheba.co.il/מחלקת_טיפול_נמרץ_ילדים_עש_קלאודיו_כהן
/clinics/Intensive_Care/415.htm\thttps://yeladim.sheba.co.il/מתנדבים_במכון
/clinics/Master_anesthesia_Osdtzih/\thttps://yeladim.sheba.co.il/היחידה_להרדמה_ולסדציה
/clinics/Nephrology_and_hypertension_clinic/\thttps://yeladim.sheba.co.il/היחידה_לנפרולוגיה_ויתר_לחץ_דם
/clinics/Neurology_Clinic/\thttps://yeladim.sheba.co.il/היחידה_לניורולוגיה_של_הילד
/clinics/Neurology_Clinic/Multiple_Sclerosis_Clinic/\thttps://yeladim.sheba.co.il/מרפאת_טרשת_נפוצה
/clinics/Neurosurgery_Unit/\thttps://yeladim.sheba.co.il/היחידה_לנוירוכירורגיה
/clinics/Nursing_system/\thttps://yeladim.sheba.co.il/מערך_הסיעוד
/clinics/nutrition_clinic/\thttps://yeladim.sheba.co.il/השירות_לתזונת_ילדים
/clinics/orthopedics_clinis/\thttps://yeladim.sheba.co.il/מרפאה_אורתופדית_ילדים
/clinics/orthopedics_clinis/Hip_joints_US/\thttps://yeladim.sheba.co.il/מרפאת_אולטראסאונד_ילודים
/clinics/PKU_Clinic/\thttps://yeladim.sheba.co.il/PKU_מרפאת-
/clinics/Premature_newborns_/\thttps://yeladim.sheba.co.il/מחלקת_ילודים_ופגים
/clinics/Premature_newborns_/55.htm\thttps://yeladim.sheba.co.il/מחלקת_ילודים
/clinics/Premature_newborns_/59.htm\thttps://yeladim.sheba.co.il/57410
/clinics/Premature_newborns_/60.htm\thttps://yeladim.sheba.co.il/מחלקת_פגים
/clinics/psychiatry_unit/\thttps://yeladim.sheba.co.il/פסיכיאטריה_ילדים
/clinics/psychiatry_unit/526.htm\thttps://yeladim.sheba.co.il/היחידה_לפסיכיאטריה_של_הילד_והמתבגר
/clinics/psychiatry_unit/528.htm\thttps://yeladim.sheba.co.il/המעבדה_לנוירופסיכיאטריה_של_הילד
/clinics/psychiatry_unit/anxiety/\thttps://yeladim.sheba.co.il/מרפאה_להפרעות_חרדה
/clinics/psychiatry_unit/behavioral_genetics_clinic/\thttps://yeladim.sheba.co.il/המרפאה_לגנטיקה_התנהגותית
/clinics/psychiatry_unit/keshev/\thttps://yeladim.sheba.co.il/מרפאת_קשב_ולמידה
/clinics/psychiatry_unit/psychiatry_Daycare/\thttps://yeladim.sheba.co.il/מעון_יום_פסיכיאטרי_לילדים
/clinics/psychiatry_unit/psychiatry_Daycare/524.htm\thttps://yeladim.sheba.co.il/מעון_יום_פסיכיאטרי_לילדים
/clinics/psychiatry_unit/soma/\thttps://yeladim.sheba.co.il/מרפאה_לפסיכולוגיה_רפואית
/clinics/Psychosomatic_ward_for_kids/\thttps://yeladim.sheba.co.il/פסיכוסומטיקה_בילדים
/clinics/Rheumatology_Clinic/\thttps://yeladim.sheba.co.il/מרפאת_ראומטולוגיה_ילדים
/clinics/Rheumatology_Clinic/307.htm\thttps://yeladim.sheba.co.il/מרפאת_ראומטולוגיה_ילדים
/clinics/Rhythm_disorders_clinic_for_children/\thttps://yeladim.sheba.co.il/המרפאה_לאלקטרופיזיולוגיה_בילדים_ובמומי_לב_מולדים
/clinics/School_Rehabilitation_Weizmann_Center/\thttps://yeladim.sheba.co.il/מרכז_שיקום_על_שם_ויצמן
/clinics/Sensory_garden/\thttps://yeladim.sheba.co.il/גן_החושים
/clinics/Skin_Clinic/\thttps://yeladim.sheba.co.il/מרפאת_עור_ילדים
/clinics/Social_services/\thttps://yeladim.sheba.co.il/השירות_הסוציאלי_ילדים
/clinics/Sports_Clinic/\thttps://yeladim.sheba.co.il/מרפאת_ספורט_תזונה_ואורח_חיים_בריא
/clinics/Sports_Clinic/256.htm\thttps://yeladim.sheba.co.il/מאמר_המלצות_לפעילות_גופנית_ילדים
/clinics/Sports_Clinic/257.htm\thttps://yeladim.sheba.co.il/מהי_רפואת_ספורט_ילדים
/clinics/Sports_Clinic/258.htm\thttps://yeladim.sheba.co.il/מאמר_המלצות_לפעילות_גופנית_ילדים
/clinics/Sports_Clinic/278.htm\thttps://yeladim.sheba.co.il/אורח_חיים_בריא_הוא_רפואה_לכל_דבר
/clinics/Surgical_children/\thttps://yeladim.sheba.co.il/כירורגית_ילדים
/clinics/Surgical_children/464.htm\thttps://yeladim.sheba.co.il/מרפאה_לטיפול_בהשמנת_יתר_קיצונית_במתבגרים
/clinics/Tuberous_Sclerosis/\thttps://yeladim.sheba.co.il/מרפאת_טוברוס_סקלרוזיס
/clinics/Unit_lung_disease_Children_National_Center_for_CF/\thttps://yeladim.sheba.co.il/תזונה_ריאות_וסיסטיק_פיברוזיס_ילדים
/clinics/Urgent_Medicine/\thttps://yeladim.sheba.co.il/המחלקה_לרפואה_דחופה_עש_רפאל_כהן
/clinics/Urology_clinic/\thttps://yeladim.sheba.co.il/מרפאת_אורולוגיה_לילדים
/Contact_Us_/\thttps://yeladim.sheba.co.il/צור_קשר
/department/Child_Development_Institute/\thttps://yeladim.sheba.co.il/המכון_להתפתחות_הילד
/department/Children_North/\thttps://yeladim.sheba.co.il/%D7%9E%D7%97%D7%9C%D7%A7%D7%AA_%D7%99%D7%9C%D7%93%D7%99%D7%9D_%D7%90_%D7%A6%D7%A4%D7%95%D7%9F
/department/Children_Rehabilitation/\thttps://yeladim.sheba.co.il/שיקום_ילדים
/department/Children_South/\thttps://yeladim.sheba.co.il/%D7%99%D7%9C%D7%93%D7%99%D7%9D_%D7%91_%D7%93%D7%A8%D7%95%D7%9D
/department/Endocrinology_Clinic_juvenile_diabetes/\thttps://yeladim.sheba.co.il/סוכרת_נעורים
/department/Gaster_Clinic/\thttps://yeladim.sheba.co.il/היחידה_לגסטרואנטרולוגיה_לילדים
/department/heart_defects_clinic/\thttps://yeladim.sheba.co.il/המרפאה_לאלקטרופיזיולוגיה_בילדים_ובמומי_לב_מולדים
/department/Hmtoaonkology/\thttps://yeladim.sheba.co.il/המטו-אונקולוגיה_ילדים
/department/Hmtoaonkology/Beit_Wiesel/\thttps://yeladim.sheba.co.il/משכן_מריון_ואלי_ויזל
/department/Imaging_unit/150.htm\thttps://yeladim.sheba.co.il/הכנה_לבדיקת_MRI
/department/Immunology_clinic/\thttps://yeladim.sheba.co.il/מרפאת_אימונולוגיה_ילדים
/department/Intensive_Care/\thttps://yeladim.sheba.co.il/מחלקת_טיפול_נמרץ_ילדים_עש_קלאודיו_כהן
/department/Neurology_Clinic/\thttps://yeladim.sheba.co.il/היחידה_לניורולוגיה_של_הילד
/department/Premature_newborns_/55.htm\thttps://yeladim.sheba.co.il/מחלקת_ילודים
/department/Premature_newborns_/60.htm\thttps://yeladim.sheba.co.il/מחלקת_פגים
/department/Surgical_children/\thttps://yeladim.sheba.co.il/כירורגית_ילדים
/department/Urgent_Medicine/\thttps://yeladim.sheba.co.il/המחלקה_לרפואה_דחופה_עש_רפאל_כהן
/Departments/\thttps://yeladim.sheba.co.il/%D7%9E%D7%A8%D7%A4%D7%90%D7%95%D7%AA-%D7%99%D7%9C%D7%93%D7%99%D7%9D
/expertise/\thttps://yeladim.sheba.co.il/המרכז_הבינלאומי_אדמונד_ספרא
/545/\thttps://www.sheba.co.il/%D7%A4%D7%A8%D7%A1%D7%95%D7%9D_%D7%91%D7%90%D7%AA%D7%A8
/566/\thttps://yeladim.sheba.co.il/%D7%98%D7%9C%D7%A4%D7%95%D7%A0%D7%99%D7%9D-%D7%A1%D7%A4%D7%A8%D7%90
/573/\thttps://yeladim.sheba.co.il/%D7%98%D7%9C%D7%A4%D7%95%D7%A0%D7%99%D7%9D-%D7%A1%D7%A4%D7%A8%D7%90
/576/\thttps://yeladim.sheba.co.il/עמותות
/591/\thttps://yeladim.sheba.co.il/מילון-מושגים-בסיסיים
/606/\thttps://yeladim.sheba.co.il/פטרת_הקרקפת
/654/\thttps://yeladim.sheba.co.il/מרפאת-גסטרוסטום
/676/562.htm\thttps://yeladim.sheba.co.il/המרכז-למחקרים-קליניים
/article/\thttps://yeladim.sheba.co.il/סקירת_מחקרים_במכון_להתפתחות_הילד
/article/382.htm\thttps://yeladim.sheba.co.il/סקירת_מחקרים_במכון_להתפתחות_הילד
/article/384.htm\thttps://yeladim.sheba.co.il/פרסומים_מצגות_חוברת_תקצירים
/article/406.htm\thttps://yeladim.sheba.co.il/דרכים_לתת
/article/Articles_Library/\thttps://yeladim.sheba.co.il/מאמרים
/article/Articles_Library/118.htm\thttps://yeladim.sheba.co.il/כתבה_הנקת_תינוקות
/article/Articles_Library/119.htm\thttps://yeladim.sheba.co.il/כתבה_עיסוי_תינוקות
/article/Articles_Library/121.htm\thttps://yeladim.sheba.co.il/כתבה_הפעלת_תינוק_באמבטיה
/article/Articles_Library/122.htm\thttps://yeladim.sheba.co.il/כתבה_תינוק_בא_הביתה_בעיות_שכיחות
/article/Articles_Library/123.htm\thttps://yeladim.sheba.co.il/צעצועים_התפתחותיים
/article/Articles_Library/127.htm\thttps://yeladim.sheba.co.il/בריאות_שיני_התינוק
/article/Articles_Library/128.htm\thttps://yeladim.sheba.co.il/כתבה_בעיות_שינה_התנהגותיות
/article/Articles_Library/129.htm\thttps://yeladim.sheba.co.il/פרכוסי_חום
/article/Articles_Library/144.htm\thttps://yeladim.sheba.co.il/כתבה_אי_סבילות_לקטוז_ילדים
/article/Articles_Library/199.htm\thttps://yeladim.sheba.co.il/כתבה_השמנת-יתר_ילדים
/article/Articles_Library/205.htm\thttps://yeladim.sheba.co.il/כתבה_ברית_מילה_בשנות2000
/article/Articles_Library/212.htm\thttps://yeladim.sheba.co.il/כתבה_תרפיה_בתנועה
/article/Articles_Library/213.htm\thttps://yeladim.sheba.co.il/כתבה_טרשת_נפוצה_ילדים
/article/Articles_Library/215.htm\thttps://yeladim.sheba.co.il/כתבה_גמילה_מטיטולים
/article/Articles_Library/227.htm\thttps://yeladim.sheba.co.il/כתבה_לצאת_מהלחץ_ילדים
/article/Articles_Library/243.htm\thttps://yeladim.sheba.co.il/כתבה_פה_גדול
/article/Articles_Library/251.htm\thttps://yeladim.sheba.co.il/סדנאות_לטיפול_בהשמנת_יתר
/article/Articles_Library/268.htm\thttps://yeladim.sheba.co.il/כתבה_אמא_אני_מפחד
/article/Articles_Library/274.htm\thttps://yeladim.sheba.co.il/כתבה_הכיני_ילדך_לחורף
/article/Articles_Library/292.htm\thttps://yeladim.sheba.co.il/כתבה_הקשר_בין_אביב_לאלרגיה
/article/Articles_Library/293.htm\thttps://yeladim.sheba.co.il/כתבה_ארגון_סביבת_עבודה_לילד
/article/Articles_Library/300.htm\thttps://yeladim.sheba.co.il/כתבה_מומחים_משיבים_התפתחות_בילד
/article/Articles_Library/302.htm\thttps://yeladim.sheba.co.il/מאמרים
/article/Articles_Library/309.htm\thttps://yeladim.sheba.co.il/כתבה_שנת_תינוקות
/article/Articles_Library/310.htm\thttps://yeladim.sheba.co.il/אורח_חיים_בריא_הוא_רפואה_לכל_דבר
/article/Articles_Library/322.htm\thttps://yeladim.sheba.co.il/כתבה_להתמודד_עם_מחלות_בחורף
/article/Articles_Library/323.htm\thttps://yeladim.sheba.co.il/כתבה_חיסונים_ילדים
/article/Kidneys_and_urinary_path/\thttps://yeladim.sheba.co.il/כליות_ודרכי_השתן
/clinics/\thttps://yeladim.sheba.co.il/%D7%9E%D7%A8%D7%A4%D7%90%D7%95%D7%AA-%D7%99%D7%9C%D7%93%D7%99%D7%9D
/clinics/495.htm\thttps://yeladim.sheba.co.il/שירות_סוציאלי_המכון_להתפתחות_הילד
/clinics/A_T_national_clinic/\thttps://yeladim.sheba.co.il/AT_מרפאה_ארצית_לטיפול_בחולי
/clinics/A_T_national_clinic/488.htm\thttps://yeladim.sheba.co.il/AT_מרפאה_ארצית_לטיפול_בחולי
/clinics/Adolescent_clinic/\thttps://yeladim.sheba.co.il/מרפאת_מתבגרים
/clinics/allergy_clinic/\thttps://yeladim.sheba.co.il/מרפאת_אלרגיה_ילדים
/clinics/Cardiology_Clinic/\thttps://yeladim.sheba.co.il/מרפאת_קרדיולוגית_ילדים
/clinics/Child_Development_Institute/\thttps://yeladim.sheba.co.il/המכון_להתפתחות_הילד
/clinics/Child_Development_Institute/284.htm\thttps://yeladim.sheba.co.il/%D7%9E%D7%A8%D7%A4%D7%90%D7%95%D7%AA_%D7%94%D7%9E%D7%9B%D7%95%D7%9F_%D7%9C%D7%94%D7%AA%D7%A4%D7%AA%D7%97%D7%95%D7%AA_%D7%94%D7%99%D7%9C%D7%93
/clinics/Child_Development_Institute/285.htm\thttps://yeladim.sheba.co.il/%D7%9E%D7%A1%D7%92%D7%A8%D7%95%D7%AA_%D7%97%D7%99%D7%A0%D7%95%D7%9B%D7%99%D7%95%D7%AA_%D7%98%D7%99%D7%A4%D7%95%D7%9C%D7%99%D7%95%D7%AA
/clinics/Child_Development_Institute/289.htm\thttps://yeladim.sheba.co.il/%D7%AA%D7%97%D7%95%D7%9E%D7%99_%D7%9E%D7%97%D7%A7%D7%A8_%D7%91%D7%9E%D7%9B%D7%95%D7%9F_%D7%9C%D7%94%D7%AA%D7%A4%D7%AA%D7%97%D7%95%D7%AA_%D7%94%D7%99%D7%9C%D7%93
/clinics/Child_Development_Institute/518.htm\thttps://www.sheba.co.il/%D7%93%D7%A8%D7%95%D7%A9%D7%99%D7%9D_%D7%91%D7%A9%D7%99%D7%91%D7%90
/clinics/Child_Development_Institute/540.htm\thttps://yeladim.sheba.co.il/מוכנות_לכיתה_א
/clinics/Child_Development_Institute/541.htm\thttps://yeladim.sheba.co.il/השימוש_בטאבלט_עם_פעוטות_וילדים
/clinics/Child_Development_Institute/542.htm\thttps://yeladim.sheba.co.il/דף_מידע_להורים_מוטוריקה
/clinics/Child_Development_Institute/543.htm\thttps://yeladim.sheba.co.il/דף_מידע_להורים_גרפומוטוריקה
/clinics/Child_Development_Institute/544.htm\thttps://yeladim.sheba.co.il/מידע_להורים_הפרעה_התפתחותית_בקואורדינציה
/clinics/Child_Development_Institute/545.htm\thttps://yeladim.sheba.co.il/מידע_להורים_תקשורת_תומכת_חליפית
/clinics/Child_Development_Institute/546.htm\thttps://yeladim.sheba.co.il/%D7%9E%D7%9B%D7%95%D7%9F_%D7%9C%D7%94%D7%AA%D7%A4%D7%AA%D7%97%D7%95%D7%AA_%D7%94%D7%99%D7%9C%D7%93_%D7%9E%D7%99%D7%93%D7%A2_%D7%9C%D7%94%D7%95%D7%A8%D7%99%D7%9D
/clinics/Child_Development_Institute/552.htm\thttps://yeladim.sheba.co.il/פעילות_צוותים_פרה_רפואיים
/clinics/Child_Development_Institute/555.htm\thttps://yeladim.sheba.co.il/צהרונים
/clinics/Child_Development_Institute/68.htm\thttps://yeladim.sheba.co.il/%D7%94%D7%AA%D7%A4%D7%AA%D7%97%D7%95%D7%99%D7%95%D7%AA_%D7%A2%D7%99%D7%AA%D7%95%D7%9F_%D7%94%D7%9E%D7%A8%D7%9B%D7%96_%D7%9C%D7%94%D7%AA%D7%A4%D7%AA%D7%97%D7%95%D7%AA_%D7%94%D7%99%D7%9C%D7%93
/clinics/Child_Development_Institute/69.htm\thttps://yeladim.sheba.co.il/%D7%94%D7%AA%D7%A4%D7%AA%D7%97%D7%95%D7%99%D7%95%D7%AA_%D7%A2%D7%99%D7%AA%D7%95%D7%9F_%D7%94%D7%9E%D7%A8%D7%9B%D7%96_%D7%9C%D7%94%D7%AA%D7%A4%D7%AA%D7%97%D7%95%D7%AA_%D7%94%D7%99%D7%9C%D7%93
/clinics/Children_North/\thttps://yeladim.sheba.co.il/%D7%9E%D7%97%D7%9C%D7%A7%D7%AA_%D7%99%D7%9C%D7%93%D7%99%D7%9D_%D7%90_%D7%A6%D7%A4%D7%95%D7%9F
/clinics/Children_Rehabilitation/\thttps://yeladim.sheba.co.il/שיקום_ילדים
/clinics/Children_South/\thttps://yeladim.sheba.co.il/%D7%99%D7%9C%D7%93%D7%99%D7%9D_%D7%91_%D7%93%D7%A8%D7%95%D7%9D
/clinics/Coagulation_disorders_clinic/\thttps://yeladim.sheba.co.il/מרפאה_להפרעות_קרישה
/clinics/Dental_clinic/\thttps://yeladim.sheba.co.il/מרפאת_שיניים_לילדים
/clinics/eating_disorder_clinic/\thttps://yeladim.sheba.co.il/המרפאה_להפרעות_אכילה_לילדים_ונוער
/clinics/Endocrinology_Clinic_juvenile_diabetes/\thttps://yeladim.sheba.co.il/סוכרת_נעורים
/clinics/Endocrinology_Clinic_juvenile_diabetes/176.htm\thttps://yeladim.sheba.co.il/קומה_נמוכה
/clinics/Endocrinology_Clinic_juvenile_diabetes/179.htm\thttps://yeladim.sheba.co.il/דפי_מידע_סוכרת_נעורים
/clinics/Eye_clinic/\thttps://yeladim.sheba.co.il/מרפאת_עיניים_לילדים
/clinics/Gaster_Clinic/\thttps://yeladim.sheba.co.il/היחידה_לגסטרואנטרולוגיה_לילדים
/clinics/Gaster_Clinic/193.htm\thttps://yeladim.sheba.co.il/מרפאת-גסטרוסטום
/clinics/Gaster_Clinic/291.htm\thttps://yeladim.sheba.co.il/מרפאה_לבעיות_אכילה_בליעה_ושגשוג_בילדים_בגיל_הרך
/clinics/Gaster_Clinic/336.htm\thttps://yeladim.sheba.co.il/עצירות
/clinics/Gaster_Clinic/476.htm\thttps://yeladim.sheba.co.il/מרפאה_תסמונת_המעי_הקצר_ילדים
/clinics/heart_defects_clinic/\thttps://yeladim.sheba.co.il/המרפאה_לאלקטרופיזיולוגיה_בילדים_ובמומי_לב_מולדים
/clinics/heart_defects_clinic/ECMO\thttps://yeladim.sheba.co.il/חימצון_חוץ_גופי_אקמו
/clinics/Hmtoaonkology/\thttps://yeladim.sheba.co.il/המטו-אונקולוגיה_ילדים
/clinics/Hmtoaonkology/Department_of_hospitalization/\thttps://yeladim.sheba.co.il/מחלקת_האישפוז
/clinics/Hmtoaonkology/Institute_Hhmto___Oncology/\thttps://yeladim.sheba.co.il/המכון_ההמטו-אונקולוגי
/clinics/Hmtoaonkology/Institute_Hhmto___Oncology/Beit_Wiesel/\thttps://yeladim.sheba.co.il/משכן_מריון_ואלי_ויזל
/clinics/Hmtoaonkology/Institute_Hhmto___Oncology/Contact_Us/\thttps://yeladim.sheba.co.il/צור_קשר
/clinics/Imaging_unit/\thttps://yeladim.sheba.co.il/דפי_מידע_דימות_ילדים
/clinics/Imaging_unit/112.htm\thttps://yeladim.sheba.co.il/הכנה_לבדיקת_MRI
/clinics/Immunology_clinic/\thttps://yeladim.sheba.co.il/מרפאת_אימונולוגיה_ילדים
/clinics/Infectious_diseases_clinic/\thttps://yeladim.sheba.co.il/מרפאה_למחלות_זיהומיות
/clinics/Intensive_Care/\thttps://yeladim.sheba.co.il/מחלקת_טיפול_נמרץ_ילדים_עש_קלאודיו_כהן
/clinics/Intensive_Care/415.htm\thttps://yeladim.sheba.co.il/מתנדבים_במכון
/clinics/Master_anesthesia_Osdtzih/\thttps://yeladim.sheba.co.il/היחידה_להרדמה_ולסדציה
/clinics/Nephrology_and_hypertension_clinic/\thttps://yeladim.sheba.co.il/היחידה_לנפרולוגיה_ויתר_לחץ_דם
/clinics/Neurology_Clinic/\thttps://yeladim.sheba.co.il/היחידה_לניורולוגיה_של_הילד
/clinics/Neurology_Clinic/Multiple_Sclerosis_Clinic/\thttps://yeladim.sheba.co.il/מרפאת_טרשת_נפוצה
/clinics/Neurosurgery_Unit/\thttps://yeladim.sheba.co.il/היחידה_לנוירוכירורגיה
/clinics/Nursing_system/\thttps://yeladim.sheba.co.il/מערך_הסיעוד
/clinics/nutrition_clinic/\thttps://yeladim.sheba.co.il/השירות_לתזונת_ילדים
/clinics/orthopedics_clinis/\thttps://yeladim.sheba.co.il/מרפאה_אורתופדית_ילדים
/clinics/orthopedics_clinis/Hip_joints_US/\thttps://yeladim.sheba.co.il/מרפאת_אולטראסאונד_ילודים
/clinics/PKU_Clinic/\thttps://yeladim.sheba.co.il/PKU_מרפאת-
/clinics/Premature_newborns_/\thttps://yeladim.sheba.co.il/מחלקת_ילודים_ופגים
/clinics/Premature_newborns_/55.htm\thttps://yeladim.sheba.co.il/מחלקת_ילודים
/clinics/Premature_newborns_/59.htm\thttps://yeladim.sheba.co.il/57410
/clinics/Premature_newborns_/60.htm\thttps://yeladim.sheba.co.il/מחלקת_פגים
/clinics/psychiatry_unit/\thttps://yeladim.sheba.co.il/פסיכיאטריה_ילדים
/clinics/psychiatry_unit/526.htm\thttps://yeladim.sheba.co.il/היחידה_לפסיכיאטריה_של_הילד_והמתבגר
/clinics/psychiatry_unit/528.htm\thttps://yeladim.sheba.co.il/המעבדה_לנוירופסיכיאטריה_של_הילד
/clinics/psychiatry_unit/anxiety/\thttps://yeladim.sheba.co.il/מרפאה_להפרעות_חרדה
/clinics/psychiatry_unit/behavioral_genetics_clinic/\thttps://yeladim.sheba.co.il/המרפאה_לגנטיקה_התנהגותית
/clinics/psychiatry_unit/keshev/\thttps://yeladim.sheba.co.il/מרפאת_קשב_ולמידה
/clinics/psychiatry_unit/psychiatry_Daycare/\thttps://yeladim.sheba.co.il/מעון_יום_פסיכיאטרי_לילדים
/clinics/psychiatry_unit/psychiatry_Daycare/524.htm\thttps://yeladim.sheba.co.il/מעון_יום_פסיכיאטרי_לילדים
/clinics/psychiatry_unit/soma/\thttps://yeladim.sheba.co.il/מרפאה_לפסיכולוגיה_רפואית
/clinics/Psychosomatic_ward_for_kids/\thttps://yeladim.sheba.co.il/פסיכוסומטיקה_בילדים
/clinics/Rheumatology_Clinic/\thttps://yeladim.sheba.co.il/מרפאת_ראומטולוגיה_ילדים
/clinics/Rheumatology_Clinic/307.htm\thttps://yeladim.sheba.co.il/מרפאת_ראומטולוגיה_ילדים
/clinics/Rhythm_disorders_clinic_for_children/\thttps://yeladim.sheba.co.il/המרפאה_לאלקטרופיזיולוגיה_בילדים_ובמומי_לב_מולדים
/clinics/School_Rehabilitation_Weizmann_Center/\thttps://yeladim.sheba.co.il/מרכז_שיקום_על_שם_ויצמן
/clinics/Sensory_garden/\thttps://yeladim.sheba.co.il/גן_החושים
/clinics/Skin_Clinic/\thttps://yeladim.sheba.co.il/מרפאת_עור_ילדים
/clinics/Social_services/\thttps://yeladim.sheba.co.il/השירות_הסוציאלי_ילדים
/clinics/Sports_Clinic/\thttps://yeladim.sheba.co.il/מרפאת_ספורט_תזונה_ואורח_חיים_בריא
/clinics/Sports_Clinic/256.htm\thttps://yeladim.sheba.co.il/מאמר_המלצות_לפעילות_גופנית_ילדים
/clinics/Sports_Clinic/257.htm\thttps://yeladim.sheba.co.il/מהי_רפואת_ספורט_ילדים
/clinics/Sports_Clinic/258.htm\thttps://yeladim.sheba.co.il/מאמר_המלצות_לפעילות_גופנית_ילדים
/clinics/Sports_Clinic/278.htm\thttps://yeladim.sheba.co.il/אורח_חיים_בריא_הוא_רפואה_לכל_דבר
/clinics/Surgical_children/\thttps://yeladim.sheba.co.il/כירורגית_ילדים
/clinics/Surgical_children/464.htm\thttps://yeladim.sheba.co.il/מרפאה_לטיפול_בהשמנת_יתר_קיצונית_במתבגרים
/clinics/Tuberous_Sclerosis/\thttps://yeladim.sheba.co.il/מרפאת_טוברוס_סקלרוזיס
/clinics/Unit_lung_disease_Children_National_Center_for_CF/\thttps://yeladim.sheba.co.il/תזונה_ריאות_וסיסטיק_פיברוזיס_ילדים
/clinics/Urgent_Medicine/\thttps://yeladim.sheba.co.il/המחלקה_לרפואה_דחופה_עש_רפאל_כהן
/clinics/Urology_clinic/\thttps://yeladim.sheba.co.il/מרפאת_אורולוגיה_לילדים
/Contact_Us_/\thttps://yeladim.sheba.co.il/צור_קשר
/department/Child_Development_Institute/\thttps://yeladim.sheba.co.il/המכון_להתפתחות_הילד
/department/Children_North/\thttps://yeladim.sheba.co.il/%D7%9E%D7%97%D7%9C%D7%A7%D7%AA_%D7%99%D7%9C%D7%93%D7%99%D7%9D_%D7%90_%D7%A6%D7%A4%D7%95%D7%9F
/department/Children_Rehabilitation/\thttps://yeladim.sheba.co.il/שיקום_ילדים
/department/Children_South/\thttps://yeladim.sheba.co.il/%D7%99%D7%9C%D7%93%D7%99%D7%9D_%D7%91_%D7%93%D7%A8%D7%95%D7%9D
/department/Endocrinology_Clinic_juvenile_diabetes/\thttps://yeladim.sheba.co.il/סוכרת_נעורים
/department/Gaster_Clinic/\thttps://yeladim.sheba.co.il/היחידה_לגסטרואנטרולוגיה_לילדים
/department/heart_defects_clinic/\thttps://yeladim.sheba.co.il/המרפאה_לאלקטרופיזיולוגיה_בילדים_ובמומי_לב_מולדים
/department/Hmtoaonkology/\thttps://yeladim.sheba.co.il/המטו-אונקולוגיה_ילדים
/department/Hmtoaonkology/Beit_Wiesel/\thttps://yeladim.sheba.co.il/משכן_מריון_ואלי_ויזל
/department/Imaging_unit/150.htm\thttps://yeladim.sheba.co.il/הכנה_לבדיקת_MRI
/department/Immunology_clinic/\thttps://yeladim.sheba.co.il/מרפאת_אימונולוגיה_ילדים
/department/Intensive_Care/\thttps://yeladim.sheba.co.il/מחלקת_טיפול_נמרץ_ילדים_עש_קלאודיו_כהן
/department/Neurology_Clinic/\thttps://yeladim.sheba.co.il/היחידה_לניורולוגיה_של_הילד
/department/Premature_newborns_/55.htm\thttps://yeladim.sheba.co.il/מחלקת_ילודים
/department/Premature_newborns_/60.htm\thttps://yeladim.sheba.co.il/מחלקת_פגים
/department/Surgical_children/\thttps://yeladim.sheba.co.il/כירורגית_ילדים
/department/Urgent_Medicine/\thttps://yeladim.sheba.co.il/המחלקה_לרפואה_דחופה_עש_רפאל_כהן
/Departments/\thttps://yeladim.sheba.co.il/%D7%9E%D7%A8%D7%A4%D7%90%D7%95%D7%AA-%D7%99%D7%9C%D7%93%D7%99%D7%9D
/expertise/\thttps://yeladim.sheba.co.il/המרכז_הבינלאומי_אדמונד_ספרא



/news_room/397.htm\thttps://yeladim.sheba.co.il/%D7%93%D7%91%D7%A8-%D7%9E%D7%A0%D7%94%D7%9C%D7%AA-%D7%94%D7%9E%D7%9B%D7%95%D7%9F
/news_room/387.htm\thttps://yeladim.sheba.co.il/הכנס-השנתי-של-המכון-להתפתחות
/news_room/389.htm\thttps://yeladim.sheba.co.il/המרפאה-להפרעות-שינה
/news_room/390.htm\thttps://yeladim.sheba.co.il/פיתוח-ביטחון-עצמי-בקרב-ילדים
/news_room/391.htm\thttps://yeladim.sheba.co.il/לקות-שפתית
/news_room/392.htm\thttps://yeladim.sheba.co.il/תרומתו-של-הליצן-הרפואי-להתערבות-בקרב-ילדים-בספקטרום-האוטיזם
/news_room/393.htm\thttps://yeladim.sheba.co.il/תסמונת-האיקס-השביר
/news_room/394.htm\thttps://yeladim.sheba.co.il/אילו-מכשירי-חימום-בטוחים-לשימוש-בסביבת-ילדים
/news_room/395.htm\thttps://yeladim.sheba.co.il/חגי-תשרי-במעונות-ובגנים
/news_room/396.htm\thttps://yeladim.sheba.co.il/מור-פרי-קופרשטיין-תרפיסטית-בתנועה

/news_room/402.htm\thttps://yeladim.sheba.co.il/מהם-אמצעי-הטיפול-בהפרעות-קשב-וריכוז
/news_room/403.htm\thttps://yeladim.sheba.co.il/יום-עיון-בנושא-חשיבה-חברתית
/news_room/399.htm\thttps://yeladim.sheba.co.il/אבחון-פסיכולוגי-התפתחותי-קווים-לדמותו
/news_room/405.htm\thttps://yeladim.sheba.co.il/הכנס-השנתי-השמיני-של-מרכז-קשת-והמכון-להתפתחות-הילד
/news_room/407.htm\thttps://yeladim.sheba.co.il/ראיון-עם-דר-עמנואל-בירנבאום
/news_room/400.htm\thttps://yeladim.sheba.co.il/שרי-אבן-מספרת-על-התנדבותה-במכון-להתפתחות-הילד-בתל-השומר
/news_room/406.htm\thttps://yeladim.sheba.co.il/שירלי-פישר-עובדת-מצטיינת
/news_room/401.htm\thttps://yeladim.sheba.co.il/פורים-ופסח-בגנים-ובמעונות
/news_room/408.htm\thttps://yeladim.sheba.co.il/שמחה-רבה-שמחה-רבה-אביב-הגיע-פסח-בא
/news_room/404.htm\thttps://yeladim.sheba.co.il/דנה-הראל-מתמחה-בפסיכולוגיה-התפתחותית

/clinics/Child_Development_Institute/577.htm\thttps://yeladim.sheba.co.il/דברי-פתיחה-קיץ-2017
/clinics/Child_Development_Institute/565.htm\thttps://yeladim.sheba.co.il/יום-הוקרה-לעובדים
/clinics/Child_Development_Institute/573.htm\thttps://yeladim.sheba.co.il/חשיבה-חברתית
/clinics/Child_Development_Institute/571.htm\thttps://yeladim.sheba.co.il/העמותה-לתסמונת-האיקס-השביר-בישראל-קיימה-יום-כיף-למשפחות
/clinics/Child_Development_Institute/574.htm\thttps://yeladim.sheba.co.il/זורם-עם-הזרם
/clinics/Child_Development_Institute/568.htm\thttps://yeladim.sheba.co.il/נופש-משפחתי-בחודשי-הקיץ
/clinics/Child_Development_Institute/576.htm\thttps://yeladim.sheba.co.il/כיצד-להכין-את-ילדכם-למעבר-לגן-חדש
/clinics/Child_Development_Institute/572.htm\thttps://yeladim.sheba.co.il/הכירו-את-מחלקת-המחקר-של-המכון-להתפתחות
/clinics/Child_Development_Institute/575.htm\thttps://yeladim.sheba.co.il/חוגגים-סוף-שנה-במעון-קשת
/clinics/Child_Development_Institute/570.htm\thttps://yeladim.sheba.co.il/הגינה-הטיפולית-בגן-האבחוני
/clinics/Child_Development_Institute/566.htm\thttps://yeladim.sheba.co.il/ברוכים-הבאים-למרוץ-השליחים-של-יום-שלישי-הגדול
/clinics/Child_Development_Institute/569.htm\thttps://yeladim.sheba.co.il/הכל-אני-יכול-בחופש-הגדול
/clinics/Child_Development_Institute/567.htm\thttps://yeladim.sheba.co.il/נעמה-שהם-קלינאית-תקשורת

/news_room/412.htm\thttps://yeladim.sheba.co.il/דבר-מנהלת-המכון-סתיו-2018
/news_room/413.htm\thttps://yeladim.sheba.co.il/חידושים-באוטיזם
/news_room/418.htm\thttps://yeladim.sheba.co.il/יום-הריפוי-בעיסוק-הבינלאומי
/news_room/411.htm\thttps://yeladim.sheba.co.il/משחקי-חורף
/news_room/414.htm\thttps://yeladim.sheba.co.il/רשת-חברתית
/news_room/417.htm\thttps://yeladim.sheba.co.il/ראיון-עם-היילי-ויינברג-מתמחה-מארהב
/news_room/416.htm\thttps://yeladim.sheba.co.il/פעילויות-סתיו-בגן-האבחוני
/news_room/419.htm\thttps://yeladim.sheba.co.il/טל-שני-שרמן
/news_room/410.htm\thttps://yeladim.sheba.co.il/יום-בחייו-של-פסיכולוג-במכון-להתפתחות-הילד
/news_room/409.htm\thttps://yeladim.sheba.co.il/המלצה-על-הספר-שטום
/news_room/415.htm\thttps://yeladim.sheba.co.il/פרכוסי-חום

/news_room/424.htm\thttps://yeladim.sheba.co.il/כנס-העמותה-להתפתחות-הילד-ושיקומו
/news_room/428.htm\thttps://yeladim.sheba.co.il/הישגי-המכון-להתפתחות-הילד 
/news_room/421.htm\thttps://yeladim.sheba.co.il/ראיון-פרידה-עם-דר-אשכנזי
/news_room/426.htm\thttps://yeladim.sheba.co.il/advances-in-autism
/news_room/427.htm\thttps://yeladim.sheba.co.il/טיפ-החודש-קיץ-חופש-ומילוי-מצברים
/news_room/431.htm\thttps://yeladim.sheba.co.il/איך-למנוע-כוויות-בקרב-ילדים
/news_room/423.htm\thttps://yeladim.sheba.co.il/יום-האחות-הבינלאומי
/news_room/420.htm\thttps://yeladim.sheba.co.il/חוגגים-את-חג-השבועות
/news_room/430.htm\thttps://yeladim.sheba.co.il/רונן-סדיס
/news_room/425.htm\thttps://yeladim.sheba.co.il/יום-בחייה-של-מרפאה-בעיסוק
/news_room/429.htm\thttps://yeladim.sheba.co.il/בטיחות-ברחצה-בעונת-הקיץ





/news_room/385.htm\thttps://yeladim.sheba.co.il/במנהרת-הזמן
/news_room/373.htm\thttps://yeladim.sheba.co.il/קבוצות-מוכנות-לכיתה-א
/news_room/374.htm\thttps://yeladim.sheba.co.il/המכון-להתפתחות-הילד-קיים-יום-הוקרה-לעובדים
/news_room/384.htm\thttps://yeladim.sheba.co.il/דף-פייסבוק-חדש-עלה-לאוויר-איקס-שביר
/news_room/375.htm\thttps://yeladim.sheba.co.il/זה-לא-משחק-ילדים
/news_room/376.htm\thttps://yeladim.sheba.co.il/סימנים-מוקדמים-של-לקות-תקשורת-בספקטרום-האוטיזם
/news_room/377.htm\thttps://yeladim.sheba.co.il/רבע-שעה-ביום-והפעוט-שלכם-יהיה-חכם-יותר
/news_room/378.htm\thttps://yeladim.sheba.co.il/שימוש-בטלפונים-חכמים-בקרב-ילדי-בית-ספר-יסודי-המאובחנים-עם-הפרעת-תקשורת
/news_room/379.htm\thttps://yeladim.sheba.co.il/מסיבות-וחגיגות
/news_room/382.htm\thttps://yeladim.sheba.co.il/נהנים-ונזהרים-בקיץ
/news_room/383.htm\thttps://yeladim.sheba.co.il/ענבל-פרדו-פיזיותרפיסטית-ילדים
/news_room/381.htm\thttps://yeladim.sheba.co.il/מזל-טוב-ואיחולים-לבביים-לצוות-המכון-קיץ-2016
";
?>