<?php
$redirectText=
"/press_/20.htm\thttps://eng.sheba.co.il/66819
/About_Talpiot/11.htm\thttps://talpiot.sheba.co.il/67818
/Our_Team/\thttps://talpiot.sheba.co.il/our_team
/press_/8.htm\thttps://eng.sheba.co.il/63046
/Our_Team/18.htm\thttps://talpiot.sheba.co.il/Dr_Ariel_Tessone
/Our_Team/58.htm\thttps://talpiot.sheba.co.il/Dr_Ran_Harel
/Our_Team/84.htm\thttps://talpiot.sheba.co.il/Dr_Itai_M_Pessach
/Our_Team/107.htm\thttps://talpiot.sheba.co.il/Dr_Keren_Levanon
/Our_Team/42.htm\thttps://talpiot.sheba.co.il/61718
/Our_Team/55.htm\thttps://talpiot.sheba.co.il/Dr_Raanan_Berger
/Our_Team/20.htm\thttps://talpiot.sheba.co.il/Dr_Boaz_Weisz
/Our_Team/43.htm\thttps://talpiot.sheba.co.il/61718
/Prizes_and_Awards/44.htm\thttps://talpiot.sheba.co.il/Awards_Prizes_Dr_Ben_Simon
/Prizes_and_Awards/57.htm\thttps://talpiot.sheba.co.il/Awards_Prizes_Dr_Berger
/Our_Team/130.htm\thttps://talpiot.sheba.co.il/Dr_Itai_Gat
/Prizes_and_Awards/109.htm\thttps://talpiot.sheba.co.il/Awards_Prizes_Dr_Levanon
/Our_Team/26.htm\thttps://talpiot.sheba.co.il/Dr_Amir_Tirosh
/Prizes_and_Awards/122.htm\thttps://talpiot.sheba.co.il/Awards_Dr_Paluch_Simon
/Our_Team/12.htm\thttps://talpiot.sheba.co.il/Dr_Gil_Bornstein
/Our_Team/63.htm\thttps://talpiot.sheba.co.il/Dr_Sarit_Aviel_Ronen
/Our_Team/16.htm\thttps://talpiot.sheba.co.il/Dr._Amir_Dori
/press_/\thttps://talpiot.sheba.co.il/press
/Prizes_and_Awards/46.htm\thttps://talpiot.sheba.co.il/Awards_Dr_Bornstein
/Our_Team/45.htm\thttps://talpiot.sheba.co.il/61716
/Prizes_and_Awards/65.htm\thttps://talpiot.sheba.co.il/Awards_Dr_Ronen
/press_/19.htm\thttps://talpiot.sheba.co.il/66821
/Our_Team/28.htm\thttps://talpiot.sheba.co.il/61705
/Our_Team/53.htm\thttps://talpiot.sheba.co.il/Dr_Ofer_Margalit
/Our_Team/71.htm\thttps://talpiot.sheba.co.il/Dr_Shoshana_Greenberger
/Prizes_and_Awards/119.htm\thttps://talpiot.sheba.co.il/Awards_Prizes_Dr_Margalit
/press_/7.htm\thttps://eng.sheba.co.il/63149
/Our_Team/131.htm\thttps://talpiot.sheba.co.il/Dr_Guy_Katz
/Our_Team/21.htm\thttps://talpiot.sheba.co.il/61703
/Our_Team/64.htm\thttps://talpiot.sheba.co.il/61726
/Our_Team/54.htm\thttps://talpiot.sheba.co.il/61722
/Our_Team/40.htm\thttps://talpiot.sheba.co.il/Dr_Gal_Markel
/Our_Team/35.htm\thttps://talpiot.sheba.co.il/Dr_Eyal_Nof
/Our_Team/142.htm\thttps://talpiot.sheba.co.il/Prof_Benjamin_Dekel
/Our_Team/50.htm\thttps://talpiot.sheba.co.il/Dr_Nicola_Maggio
/Our_Team/56.htm\thttps://talpiot.sheba.co.il/61723
/Research/\thttps://talpiot.sheba.co.il/Researchers_List
/Prizes_and_Awards/97.htm\thttps://talpiot.sheba.co.il/Awards_Dr_Harel
/Prizes_and_Awards/\thttps://talpiot.sheba.co.il/Prizes_and_Awards
/Prizes_and_Awards/77.htm\thttps://talpiot.sheba.co.il/Awards_Dr_Haberman
/Prizes_and_Awards/62.htm\thttps://talpiot.sheba.co.il/Awards_Prizes_Dr_Leibowitz
/Prizes_and_Awards/138.htm\thttps://talpiot.sheba.co.il/Awards_Prizes_Dr_Shouval
/Prizes_and_Awards/139.htm\thttps://talpiot.sheba.co.il/Awards_Dr_Rosen
/Prizes_and_Awards/136.htm\thttps://talpiot.sheba.co.il/Awards_Dr_Lotan
/Prizes_and_Awards/106.htm\thttps://talpiot.sheba.co.il/Awards_Dr_Fabian
/Prizes_and_Awards/112.htm\thttps://talpiot.sheba.co.il/Awards_Dr_Nevler
/Prizes_and_Awards/133.htm\thttps://talpiot.sheba.co.il/Awards_Prizes_Dr_Katz
/Activities/\thttps://talpiot.sheba.co.il/Activities
/press_/7.htm\thttps://eng.sheba.co.il/63149
/About_Talpiot/\thttps://talpiot.sheba.co.il/About
/About_Talpiot/129.htm\thttps://eng.sheba.co.il/63249
/Prizes_and_Awards/\thttps://talpiot.sheba.co.il/Prizes_and_Awards
/About_Talpiot/5.htm\thttps://talpiot.sheba.co.il/Admission
/Prizes_and_Awards/98.htm\thttps://talpiot.sheba.co.il/Dr_Gal_Markel
/press_/8.htm\thttps://talpiot.sheba.co.il/63046
/Prizes_and_Awards/31.htm\thttps://talpiot.sheba.co.il/Awards_Dr_Weisz
/Prizes_and_Awards/133.htm\thttps://talpiot.sheba.co.il/Awards_Prizes_Dr_Katz
/Prizes_and_Awards/74.htm\thttps://talpiot.sheba.co.il/Awards_Dr_Greenberger
/Prizes_and_Awards/125.htm\thttps://talpiot.sheba.co.il/Prizes_Awards_Havazelet_Heimer
/Prizes_and_Awards/72.htm\thttps://talpiot.sheba.co.il/Awards_Dr_Ben_Horin
/Prizes_and_Awards/83.htm\thttps://talpiot.sheba.co.il/Awards_Dr_Haik
/Prizes_and_Awards/46.htm\thttps://talpiot.sheba.co.il/Awards_Dr_Bornstein
/About_Talpiot/7.htm\thttps://talpiot.sheba.co.il/The_Program
/Prizes_and_Awards/112.htm\thttps://talpiot.sheba.co.il/Awards_Dr_Nevler
/Prizes_and_Awards/44.htm\thttps://talpiot.sheba.co.il/Awards_Prizes_Dr_Ben_Simon
/Our_Team/\thttps://talpiot.sheba.co.il/our_team
/Our_Team/35.htm\thttps://talpiot.sheba.co.il/Dr_Eyal_Nof
/Our_Team/12.htm\thttps://talpiot.sheba.co.il/Dr_Gil_Bornstein
/Our_Team/55.htm\thttps://talpiot.sheba.co.il/Dr_Raanan_Berger
/Our_Team/15.htm\thttps://talpiot.sheba.co.il/Dr_Amir_Herman
/Our_Team/101.htm\thttps://talpiot.sheba.co.il/Dr_Ilan_Ben_Zvi
/Our_Team/26.htm\thttps://talpiot.sheba.co.il/Dr_Amir_Tirosh
/Our_Team/66.htm\thttps://talpiot.sheba.co.il/Prof_Shali_Mazaki_Tovi
/Our_Team/56.htm\thttps://talpiot.sheba.co.il/61723
/Our_Team/142.htm\thttps://eng.sheba.co.il/Prof_Benjamin_Dekel
/Our_Team/50.htm\thttps://talpiot.sheba.co.il/Dr_Nicola_Maggio
/Our_Team/63.htm\thttps://talpiot.sheba.co.il/Dr_Sarit_Aviel_Ronen
/Our_Team/102.htm\thttps://talpiot.sheba.co.il/61719
/Our_Team/38.htm\thttps://talpiot.sheba.co.il/Dr_Eyal_Zimlichman
/Our_Team/130.htm\thttps://talpiot.sheba.co.il/Dr_Itai_Gat
/Our_Team/58.htm\thttps://talpiot.sheba.co.il/Dr_Ran_Harel
/Our_Team/81.htm\thttps://talpiot.sheba.co.il/Prof_Josef_Haik
/Our_Team/60.htm\thttps://talpiot.sheba.co.il/Dr_Raya_Leibowitz_Amit
/Our_Team/64.htm\thttps://talpiot.sheba.co.il/61726
/Prizes_and_Awards/97.htm\thttps://talpiot.sheba.co.il/Awards_Dr_Harel
/Prizes_and_Awards/109.htm\thttps://talpiot.sheba.co.il/Awards_Prizes_Dr_Levanon
/Prizes_and_Awards/37.htm\thttps://talpiot.sheba.co.il/Awards_Dr_Nof
/Our_Team/123.htm\thttps://talpiot.sheba.co.il/Dr_Gali_Havazelet_Heimer
/Activities/100.htm\thttps://talpiot.sheba.co.il/Talpiot_for_the_Community
/Prizes_and_Awards/57.htm\thttps://talpiot.sheba.co.il/Awards_Prizes_Dr_Berger
/Prizes_and_Awards/136.htm\thttps://talpiot.sheba.co.il/Awards_Dr_Lotan
/Our_Team/81.htm\thttps://talpiot.sheba.co.il/Prof_Josef_Haik
/Our_Team/82.htm\thttps://talpiot.sheba.co.il/61720
/Our_Team/40.htm\thttps://talpiot.sheba.co.il/Dr_Gal_Markel
/Our_Team/126.htm\thttps://talpiot.sheba.co.il/Dr_Elad_Maor
/Prizes_and_Awards/135.htm\thttps://talpiot.sheba.co.il/Awards_Dr_Kivity
/Our_Team/78.htm\thttps://talpiot.sheba.co.il/Dr_Yehuda_Kamari
/Our_Team/79.htm\thttps://talpiot.sheba.co.il/61702
/press_/21.htm\thttps://eng.sheba.co.il/66818
/Our_Team/61.htm\thttps://talpiot.sheba.co.il/61725
/Prizes_and_Awards/135.htm\thttps://talpiot.sheba.co.il/Awards_Dr_Kivity
/Our_Team/141.htm\thttps://talpiot.sheba.co.il/Dr_Asaf_Vivante
/Our_Team/75.htm\thttps://talpiot.sheba.co.il/Dr_Yael_Haberman
/Our_Team/42.htm\thttps://talpiot.sheba.co.il/Prof_Guy_Ben_Simon
/Prizes_and_Awards/115.htm\thttps://talpiot.sheba.co.il/Awards_Dr_Twig
/Prizes_and_Awards/137.htm\thttps://talpiot.sheba.co.il/Awards_Prizes_Dr_Pode_Shakked
/About_Talpiot/14.htm\thttps://talpiot.sheba.co.il/Healthcare_Technologies_Business_and_Services
/Prizes_and_Awards/140.htm\thttps://talpiot.sheba.co.il/Awards_Dr_Rosenzweig
/Prizes_and_Awards/65.htm\thttps://talpiot.sheba.co.il/Awards_Dr_Ronen
/Our_Team/18.htm\thttps://talpiot.sheba.co.il/Dr_Ariel_Tessone
/About_Talpiot/11.htm\thttps://talpiot.sheba.co.il/67818
/Our_Team/36.htm\thttps://talpiot.sheba.co.il/61712
/Prizes_and_Awards/32.htm\thttps://talpiot.sheba.co.il/Prizes_Awards_Dr_Gal_Yam
/Our_Team/73.htm\thttps://talpiot.sheba.co.il/61701
/press_/19.htm\thttps://talpiot.sheba.co.il/66821
/About_Talpiot/96.htm\thttps://eng.sheba.co.il/63023
/Prizes_and_Awards/115.htm\thttps://talpiot.sheba.co.il/Awards_Dr_Twig
/Prizes_and_Awards/137.htm\thttps://talpiot.sheba.co.il/Awards_Prizes_Dr_Pode_Shakked
/Our_Team/43.htm\thttps://talpiot.sheba.co.il/61718
/Prizes_and_Awards/32.htm\thttps://talpiot.sheba.co.il/Prizes_Awards_Dr_Gal_Yam
/Prizes_and_Awards/80.htm\thttps://talpiot.sheba.co.il/Awards_Dr_Kamari
/Prizes_and_Awards/106.htm\thttps://talpiot.sheba.co.il/Awards_Dr_Fabian
/Prizes_and_Awards/77.htm\thttps://talpiot.sheba.co.il/Awards_Dr_Haberman
/Prizes_and_Awards/98.htm\thttps://talpiot.sheba.co.il/Prizes_Awards_Dr_Markel
/Our_Team/16.htm\thttps://talpiot.sheba.co.il/Dr._Amir_Dori
/Our_Team/21.htm\thttps://talpiot.sheba.co.il/61703
/Prizes_and_Awards/68.htm\thttps://talpiot.sheba.co.il/Awards_Dr_Tovi
/Prizes_and_Awards/52.htm\thttps://talpiot.sheba.co.il/Awards_Prizes_Dr_Maggio
/Our_Team/78.htm\thttps://talpiot.sheba.co.il/Dr_Yehuda_Kamari
/Prizes_and_Awards/132.htm\thttps://talpiot.sheba.co.il/Awards_Dr_Gat
/Our_Team/101.htm\thttps://talpiot.sheba.co.il/Dr_Ilan_Ben_Zvi
/Our_Team/38.htm\thttps://talpiot.sheba.co.il/Dr_Eyal_Zimlichman
/press_/&&adv_search=1\thttps://talpiot.sheba.co.il/press
/Prizes_and_Awards/122.htm\thttps://talpiot.sheba.co.il/Awards_Dr_Paluch_Simon
/About_Talpiot/6.htm\thttps://talpiot.sheba.co.il/Philanthropic_Opportunities
/About_Talpiot/96.htm\thttps://eng.sheba.co.il/63023
/Prizes_and_Awards/31.htm\thttps://talpiot.sheba.co.il/Awards_Dr_Weisz
/Activities/\thttps://talpiot.sheba.co.il/Activities
/About_Talpiot/14.htm\thttps://talpiot.sheba.co.il/Healthcare_Technologies_Business_and_Services
/Prizes_and_Awards/25.htm\thttps://talpiot.sheba.co.il/Prizes_Awards_Dr_Herman
/Prizes_and_Awards/125.htm\thttps://talpiot.sheba.co.il/Prizes_Awards_Havazelet_Heimer
/Prizes_and_Awards/103.htm\thttps://talpiot.sheba.co.il/Awards_Prizes_Dr_Ben_Zvi
/Prizes_and_Awards/128.htm\thttps://talpiot.sheba.co.il/Prizes_Awards_Dr_Maor
/Prizes_and_Awards/80.htm\thttps://talpiot.sheba.co.il/Awards_Dr_Kamari
/Our_Team/76.htm\thttps://talpiot.sheba.co.il/61731
/Our_Team/67.htm\thttps://talpiot.sheba.co.il/61727
/Our_Team/110.htm\thttps://talpiot.sheba.co.il/Dr_Avinoam_Nevler
/Prizes_and_Awards/103.htm\thttps://talpiot.sheba.co.il/Awards_Prizes_Dr_Ben_Zvi
/About_Talpiot/\thttps://talpiot.sheba.co.il/About
/Prizes_and_Awards/128.htm\thttps://talpiot.sheba.co.il/Prizes_Awards_Dr_Maor
/About_Talpiot/7.htm\thttps://talpiot.sheba.co.il/The_Program
/Our_Team/66.htm\thttps://talpiot.sheba.co.il/Prof_Shali_Mazaki_Tovi
/Our_Team/67.htm\thttps://talpiot.sheba.co.il/61727
/Our_Team/41.htm\thttps://talpiot.sheba.co.il/61714
/Our_Team/51.htm\thttps://talpiot.sheba.co.il/61721
/Our_Team/15.htm\thttps://talpiot.sheba.co.il/Dr_Amir_Herman
/Prizes_and_Awards/139.htm\thttps://talpiot.sheba.co.il/Awards_Dr_Rosen
/Our_Team/33.htm\thttps://talpiot.sheba.co.il/Dr_Einav_Gal_Yam
/Our_Team/104.htm\thttps://talpiot.sheba.co.il/Dr_Didi_Fabian
/press_/\thttps://talpiot.sheba.co.il/press
/Prizes_and_Awards/138.htm\thttps://talpiot.sheba.co.il/Awards_Prizes_Dr_Shouval
/Our_Team/82.htm\thttps://talpiot.sheba.co.il/61720
/Our_Team/45.htm\thttps://talpiot.sheba.co.il/61716
/Our_Team/104.htm\thttps://talpiot.sheba.co.il/Dr_Didi_Fabian
/Our_Team/105.htm\thttps://talpiot.sheba.co.il/61709
/Our_Team/69.htm\thttps://talpiot.sheba.co.il/Dr_Shomron_Ben_Horin
/Our_Team/70.htm\thttps://talpiot.sheba.co.il/61729
/Prizes_and_Awards/22.htm\thttps://talpiot.sheba.co.il/Awards_Dr_Dori
/Our_Team/20.htm\thttps://talpiot.sheba.co.il/Dr_Boaz_Weisz
/Our_Team/27.htm\thttps://talpiot.sheba.co.il/61704
/Activities/100.htm\thttps://talpiot.sheba.co.il/Talpiot_for_the_Community
/Our_Team/30.htm\thttps://talpiot.sheba.co.il/61708
/Our_Team/28.htm\thttps://talpiot.sheba.co.il/61705
/Our_Team/79.htm\thttps://talpiot.sheba.co.il/61702
/Our_Team/34.htm\thttps://talpiot.sheba.co.il/61710
/Our_Team/111.htm\thttps://talpiot.sheba.co.il/61706
/Prizes_and_Awards/68.htm\thttps://talpiot.sheba.co.il/Awards_Dr_Tovi
/Our_Team/71.htm\thttps://talpiot.sheba.co.il/Dr_Shoshana_Greenberger
/Our_Team/73.htm\thttps://talpiot.sheba.co.il/61701
/Our_Team/39.htm\thttps://talpiot.sheba.co.il/61713
/Our_Team/59.htm\thttps://talpiot.sheba.co.il/61724
/Prizes_and_Awards/72.htm\thttps://talpiot.sheba.co.il/Awards_Dr_Ben_Horin
/Our_Team/41.htm\thttps://talpiot.sheba.co.il/61714
/Our_Team/121.htm\thttps://talpiot.sheba.co.il/61728
/Research/\thttps://talpiot.sheba.co.il/Researchers_List
/Our_Team/27.htm\thttps://talpiot.sheba.co.il/61704
/About_Talpiot/8.htm\thttps://talpiot.sheba.co.il/The_Board
/Prizes_and_Awards/119.htm\thttps://talpiot.sheba.co.il/Awards_Prizes_Dr_Margalit
/press_/22.htm\thttps://eng.sheba.co.il/66817
/Prizes_and_Awards/134.htm\thttps://talpiot.sheba.co.il/Awards_Dr_Kinori
/Our_Team/36.htm\thttps://talpiot.sheba.co.il/61712
/Our_Team/59.htm\thttps://talpiot.sheba.co.il/61724
/Prizes_and_Awards/37.htm\thttps://talpiot.sheba.co.il/Awards_Dr_Nof
/press_/20.htm\thttps://eng.sheba.co.il/66819
/Prizes_and_Awards/140.htm\thttps://talpiot.sheba.co.il/Awards_Dr_Rosenzweig
/Our_Team/51.htm\thttps://talpiot.sheba.co.il/61721
/Prizes_and_Awards/132.htm\thttps://talpiot.sheba.co.il/Awards_Dr_Gat
/Our_Team/110.htm\thttps://talpiot.sheba.co.il/Dr_Avinoam_Nevler
/Our_Team/123.htm\thttps://talpiot.sheba.co.il/Dr_Gali_Havazelet_Heimer
/Our_Team/124.htm\thttps://talpiot.sheba.co.il/61715
/About_Talpiot/6.htm\thttps://talpiot.sheba.co.il/Philanthropic_Opportunities
/Prizes_and_Awards/134.htm\thttps://talpiot.sheba.co.il/Awards_Dr_Kinori
/About_Talpiot/5.htm\thttps://talpiot.sheba.co.il/Admission
/Our_Team/39.htm\thttps://talpiot.sheba.co.il/61713
/Our_Team/107.htm\thttps://talpiot.sheba.co.il/Dr_Keren_Levanon
/Prizes_and_Awards/25.htm\thttps://talpiot.sheba.co.il/Prizes_Awards_Dr_Herman
/Our_Team/131.htm\thttps://talpiot.sheba.co.il/Dr_Guy_Katz
/About_Talpiot/129.htm\thttps://eng.sheba.co.il/63249
/Our_Team/113.htm\thttps://talpiot.sheba.co.il/Dr_Gilad_Twig
/Our_Team/60.htm\thttps://talpiot.sheba.co.il/Dr_Raya_Leibowitz_Amit
/Our_Team/69.htm\thttps://talpiot.sheba.co.il/Dr_Shomron_Ben_Horin
/Our_Team/84.htm\thttps://talpiot.sheba.co.il/Dr_Itai_M_Pessach
/Our_Team/70.htm\thttps://talpiot.sheba.co.il/61729
/Our_Team/111.htm\thttps://talpiot.sheba.co.il/61706
/Our_Team/114.htm\thttps://talpiot.sheba.co.il/61717
/Our_Team/61.htm\thttps://talpiot.sheba.co.il/61725
/Prizes_and_Awards/62.htm\thttps://talpiot.sheba.co.il/Awards_Prizes_Dr_Leibowitz
/Our_Team/126.htm\thttps://talpiot.sheba.co.il/Dr_Elad_Maor
/Our_Team/127.htm\thttps://talpiot.sheba.co.il/61711
/Our_Team/121.htm\thttps://talpiot.sheba.co.il/61728
/Our_Team/102.htm\thttps://talpiot.sheba.co.il/61719
/Prizes_and_Awards/22.htm\thttps://talpiot.sheba.co.il/Awards_Dr_Dori
/press_/22.htm\thttps://eng.sheba.co.il/66817
/Our_Team/33.htm\thttps://talpiot.sheba.co.il/Dr_Einav_Gal_Yam
/Our_Team/34.htm\thttps://talpiot.sheba.co.il/61710
/Our_Team/124.htm\thttps://talpiot.sheba.co.il/61715
/Our_Team/30.htm\thttps://talpiot.sheba.co.il/61708
/Our_Team/53.htm\thttps://talpiot.sheba.co.il/Dr_Ofer_Margalit
/Prizes_and_Awards/74.htm\thttps://talpiot.sheba.co.il/Awards_Dr_Greenberger
/Our_Team/54.htm\thttps://talpiot.sheba.co.il/61722
/Our_Team/113.htm\thttps://talpiot.sheba.co.il/Dr_Gilad_Twig
/Our_Team/114.htm\thttps://talpiot.sheba.co.il/61717
/press_/21.htm\thttps://eng.sheba.co.il/66818
/Our_Team/105.htm\thttps://talpiot.sheba.co.il/61709
/Prizes_and_Awards/52.htm\thttps://talpiot.sheba.co.il/Awards_Prizes_Dr_Maggio
/About_Talpiot/8.htm\thttps://talpiot.sheba.co.il/The_Board
/Our_Team/127.htm\thttps://talpiot.sheba.co.il/61711
/Our_Team/75.htm\thttps://talpiot.sheba.co.il/Dr_Yael_Haberman
/Our_Team/76.htm\thttps://talpiot.sheba.co.il/61731";
?>