<?php
$redirectText=
"/162/53.htm\thttps://www.sheba.co.il/41703
/162/84.htm\thttps://www.sheba.co.il/41733
/162/118.htm\thttps://www.sheba.co.il/31857
/162/36.htm\thttps://www.sheba.co.il/41686
/175/\thttps://ella.sheba.co.il/41594
/19/\thttps://ella.sheba.co.il/מכון_אלה_מרפאות
/Translational_Research_Cell_Therapy/\thttps://ella.sheba.co.il/מעבדה_נקיה
/Research_and_development/Melanoma/\thttps://www.sheba.co.il/shebaella_Melanoma
/Research_and_development/Research_Team/\thttps://ella.sheba.co.il/73600
/e/Ella_institute_news/52.htm\thttps://eng.sheba.co.il/63253
/e/Appointments/\thttps://eng.sheba.co.il/make_an_appointment
/Appointments/\thttps://ella.sheba.co.il/41578
/162/128.htm\thttps://www.sheba.co.il/31918
/e/Ella_institute_news/4.htm\thttps://ella.sheba.co.il/41591
/About_Melanoma/\thttps://www.sheba.co.il/shebaella_About_Melanoma
/Research_and_development/publication/\thttps://www.sheba.co.il/shebaella_publication
/162/52.htm\thttps://www.sheba.co.il/41702
/e/Research_and_Development_/\thttps://eng.sheba.co.il/Research_and_Development_at_the_Ella_Institute
/e/Ella_institute_news/\thttps://ella.sheba.co.il/חדשות_מכון_אלה
/e/Ella_institute_news/4.htm\thttps://www.sheba.co.il/41808
/e/Ella_institute_news/&page_num=2\thttps://ella.sheba.co.il/חדשות_מכון_אלה
/e/Ella_institute_news/&page_num=1\thttps://ella.sheba.co.il/חדשות_מכון_אלה
/e/About_us/\thttps://eng.sheba.co.il/The_Ella_Institute
/e/Ella_institute_news/&page_num=0\thttps://ella.sheba.co.il/חדשות_מכון_אלה
/162/\thttps://ella.sheba.co.il/חדשות_מכון_אלה
/162/&&adv_search=1\thttps://ella.sheba.co.il/חדשות_מכון_אלה
/162/&page_num=2\thttps://ella.sheba.co.il/חדשות_מכון_אלה
/162/&page_num=3\thttps://ella.sheba.co.il/חדשות_מכון_אלה
/162/&page_num=1\thttps://ella.sheba.co.il/חדשות_מכון_אלה
/162/&page_num=4\thttps://ella.sheba.co.il/חדשות_מכון_אלה
/162/&page_num=5\thttps://ella.sheba.co.il/חדשות_מכון_אלה
/162/&page_num=0\thttps://ella.sheba.co.il/חדשות_מכון_אלה
/162/&&adv_search=1&page_num=1\thttps://ella.sheba.co.il/חדשות_מכון_אלה
/162/&&adv_search=1&page_num=0\thttps://ella.sheba.co.il/חדשות_מכון_אלה
/162/&&adv_search=1&page_num=2\thttps://ella.sheba.co.il/חדשות_מכון_אלה
/162/&&adv_search=1&page_num=3\thttps://ella.sheba.co.il/חדשות_מכון_אלה
/Research_and_development/Research_Team/37.htm\thttps://www.sheba.co.il/shebaella_Research_Team
/e/_Clinics/\thttps://eng.sheba.co.il/ella_Clinics
/Immunotherapy_TIL_/\thttps://ella.sheba.co.il/41793
/162/46.htm\thttps://www.sheba.co.il/41696
/e/Research_and_Development_/\thttps://eng.sheba.co.il/Research_and_Development_at_the_Ella_Institute
/162/122.htm\thttps://ella.sheba.co.il/31862
/clinics/\thttps://eng.sheba.co.il/ella_Clinics
/135/\thttps://ella.sheba.co.il/הטיפול_במלנומה
/e/Medical_Staff/\thttps://eng.sheba.co.il/Ella_medical_staff
/e/Medical_Staff/22.htm\thttps://eng.sheba.co.il/Publication_Prof_Jacob_Schachter
/e/Research_and_Development_/Research_team_/\thttps://eng.sheba.co.il/73456
/e/Ella_institute_news/\thttps://ella.sheba.co.il/חדשות_מכון_אלה
/e/Research_and_Development_/TIL_Immunotherapy_/\thttps://eng.sheba.co.il/TIL_immunotherapy
/e/About_us/\thttps://eng.sheba.co.il/The_Ella_Institute
/e/Research_and_Development_/Scientific_Publications/\thttps://eng.sheba.co.il/Daibetis_Scientific_Publications
/e/_Clinics/\thttps://eng.sheba.co.il/ella_Clinics
/Research_and_development/Research_Team/50.htm\thttps://ella.sheba.co.il/אורית_יצחקי_פרסומים
/Medical_Staff_/36.htm\thttps://www.sheba.co.il/shebaella_Medical_Staff_
/e/Research_and_Development_/Scientific_Publications/\thttps://eng.sheba.co.il/Daibetis_Scientific_Publications
/e/Research_and_Development_/Research_team_/7.htm\thttps://eng.sheba.co.il/research_team_at_Ella_institute
/e/Ella_institute_news/&page_num=2\thttps://ella.sheba.co.il/חדשות_מכון_אלה
/e/Ella_institute_news/&page_num=1\thttps://ella.sheba.co.il/חדשות_מכון_אלה
/e/Ella_institute_news/&page_num=0\thttps://ella.sheba.co.il/חדשות_מכון_אלה
/e/Contact_Us/\thttps://eng.sheba.co.il/41906
/Research_and_development/Immunotherapy_TIL/\thttps://www.sheba.co.il/shebaella_Immunotherapy_TIL
/e/Contact_Us/\thttps://eng.sheba.co.il/41906
/e/Appointments/\thttps://eng.sheba.co.il/make_an_appointment
/e/Research_and_Development_/Research_team_/6.htm\thttps://eng.sheba.co.il/research_team_at_Ella_institute
/Research_and_development/Research_Team/38.htm\thttps://ella.sheba.co.il/פרסומים_של_דר_סיון_ספוז'ניק_דנון
/162/121.htm\thttps://www.sheba.co.il/31861
/e/Research_and_Development_/Research_team_/\thttps://eng.sheba.co.il/research_team_at_Ella_institute
/e/Research_and_Development_/Research_team_/5.htm\thttps://eng.sheba.co.il/research_team_at_Ella_institute
/e/Research_and_Development_/Research_team_/8.htm\thttps://eng.sheba.co.il/research_team_at_Ella_institute
/e/Research_and_Development_/Research_team_/6.htm\thttps://eng.sheba.co.il/research_team_at_Ella_institute
/162/&adv_search=1&page_num=5\thttps://ella.sheba.co.il/חדשות_מכון_אלה
/162/&adv_search=1&page_num=4\thttps://ella.sheba.co.il/חדשות_מכון_אלה
/162/&adv_search=1&page_num=2\thttps://ella.sheba.co.il/חדשות_מכון_אלה
/162/&adv_search=1&page_num=3\thttps://ella.sheba.co.il/חדשות_מכון_אלה
/162/&adv_search=1&page_num=0\thttps://ella.sheba.co.il/חדשות_מכון_אלה
/162/&adv_search=1&page_num=1\thttps://ella.sheba.co.il/חדשות_מכון_אלה
/e/Research_and_Development_/TIL_Immunotherapy_/\thttps://eng.sheba.co.il/TIL_immunotherapy
/e/Ella_institute_news/&&adv_search=1\thttps://ella.sheba.co.il/חדשות_מכון_אלה
/e/Ella_institute_news/&adv_search=1&page_num=1\thttps://ella.sheba.co.il/חדשות_מכון_אלה
/e/Ella_institute_news/&adv_search=1&page_num=0\thttps://ella.sheba.co.il/חדשות_מכון_אלה
/e/Ella_institute_news/&adv_search=1&page_num=2\thttps://ella.sheba.co.il/חדשות_מכון_אלה
/e/Ella_institute_news/&&adv_search=1&page_num=1\thttps://ella.sheba.co.il/חדשות_מכון_אלה
/e/Ella_institute_news/&&adv_search=1&page_num=2\thttps://ella.sheba.co.il/חדשות_מכון_אלה
/e/Ella_institute_news/&&adv_search=1&page_num=0\thttps://ella.sheba.co.il/חדשות_מכון_אלה
/e/Research_and_Development_/Research_team_/7.htm\thttps://eng.sheba.co.il/research_team_at_Ella_institute
/162/&&adv_search=1&page_num=5\thttps://ella.sheba.co.il/חדשות_מכון_אלה
/162/&&adv_search=1&page_num=4\thttps://ella.sheba.co.il/חדשות_מכון_אלה
/162/126.htm\thttps://www.sheba.co.il/ella.sheba.co.il/משרה_פנויה_לרופא_אונקולוג
/162/53.htm\thttps://www.sheba.co.il/41703
/162/118.htm\thttps://www.sheba.co.il/31857
/Appointments/\thttps://eng.sheba.co.il/make_an_appointment
/19/\thttps://ella.sheba.co.il/מכון_אלה_מרפאות
/175/\thttps://ella.sheba.co.il/41594
/Research_and_development/Research_Team/\thttps://www.sheba.co.il/shebaella_Research_Team
/162/36.htm\thttps://www.sheba.co.il/41686
/162/\thttps://ella.sheba.co.il/חדשות_מכון_אלה
/Research_and_development/Research_Team/50.htm\thttps://ella.sheba.co.il/אורית_יצחקי_פרסומים
/Medical_Staff_/\thttps://ella.sheba.co.il/41573
/Research_and_development/publication/\thttps://www.sheba.co.il/shebaella_publication
/Research_and_development/Research_Team/31.htm\thttps://www.sheba.co.il/shebaella_Research_Team
/Research_and_development/Research_Team/38.htm\thttps://ella.sheba.co.il/פרסומים_של_דר_סיון_ספוז'ניק_דנון
/162/&&adv_search=1\thttps://ella.sheba.co.il/חדשות_מכון_אלה
/162/&adv_search=1&page_num=4\thttps://ella.sheba.co.il/חדשות_מכון_אלה
/162/&page_num=5\thttps://ella.sheba.co.il/חדשות_מכון_אלה
/162/&page_num=4\thttps://ella.sheba.co.il/חדשות_מכון_אלה
/162/&adv_search=1&page_num=5\thttps://ella.sheba.co.il/חדשות_מכון_אלה
/162/&page_num=3\thttps://ella.sheba.co.il/חדשות_מכון_אלה
/162/&adv_search=1&page_num=3\thttps://ella.sheba.co.il/חדשות_מכון_אלה
/162/&adv_search=1&page_num=0\thttps://ella.sheba.co.il/חדשות_מכון_אלה
/162/&adv_search=1&page_num=2\thttps://ella.sheba.co.il/חדשות_מכון_אלה
/162/&adv_search=1&page_num=1\thttps://ella.sheba.co.il/חדשות_מכון_אלה
/162/&page_num=2\thttps://ella.sheba.co.il/חדשות_מכון_אלה
/162/&page_num=1\thttps://ella.sheba.co.il/חדשות_מכון_אלה
/clinical_research/\thttps://ella.sheba.co.il/מחקרים_קליניים_מכון_אלה
/162/52.htm\thttps://www.sheba.co.il/41702
/162/46.htm\thttps://ella.sheba.co.il/41696
/119/\thttps://ella.sheba.co.il/אודות_מכון_אלה
/162/&page_num=0\thttps://ella.sheba.co.il/חדשות_מכון_אלה
/clinics/\thttps://eng.sheba.co.il/ella_Clinics
/Research_and_development/Immunotherapy_TIL/\thttps://www.sheba.co.il/shebaella_Immunotherapy_TIL
/Contact_Us/\thttps://ella.sheba.co.il/צור_קשר_מכון_אלה
/Research_and_development/Melanoma/\thttps://www.sheba.co.il/shebaella_Melanoma
/162/122.htm\thttps://ella.sheba.co.il/31862
/162/&&adv_search=1&page_num=4\thttps://ella.sheba.co.il/חדשות_מכון_אלה
/162/&&adv_search=1&page_num=3\thttps://ella.sheba.co.il/חדשות_מכון_אלה
/162/&&adv_search=1&page_num=2\thttps://ella.sheba.co.il/חדשות_מכון_אלה
/162/&&adv_search=1&page_num=0\thttps://ella.sheba.co.il/חדשות_מכון_אלה
/162/&&adv_search=1&page_num=1\thttps://ella.sheba.co.il/חדשות_מכון_אלה
/162/84.htm\thttps://www.sheba.co.il/41733
/Medical_Staff_/36.htm\thttps://www.sheba.co.il/shebaella_Medical_Staff_
/162/&&adv_search=1&page_num=5\thttps://ella.sheba.co.il/חדשות_מכון_אלה
/Links_to_information_sites/\thttps://ella.sheba.co.il/קישורים_לאתרי_מידע
/About_Melanoma/\thttps://www.sheba.co.il/shebaella_About_Melanoma
/Immunotherapy_TIL_/\thttps://ella.sheba.co.il/41793
/135/\thttps://ella.sheba.co.il/הטיפול_במלנומה
/Translational_Research_Cell_Therapy/\thttps://ella.sheba.co.il/מעבדה_נקיה
/Contact_Us/\thttps://ella.sheba.co.il/צור_קשר_מכון_אלה
/162/121.htm\thttps://ella.sheba.co.il/31861
/e/Ella_institute_news/&&adv_search=1\thttps://ella.sheba.co.il/חדשות_מכון_אלה
/e/Ella_institute_news/&adv_search=1&page_num=2\thttps://ella.sheba.co.il/חדשות_מכון_אלה
/e/Ella_institute_news/&adv_search=1&page_num=1\thttps://ella.sheba.co.il/חדשות_מכון_אלה
/e/Ella_institute_news/&&adv_search=1&page_num=1\thttps://ella.sheba.co.il/חדשות_מכון_אלה
/e/Ella_institute_news/&adv_search=1&page_num=0\thttps://ella.sheba.co.il/חדשות_מכון_אלה
/e/Ella_institute_news/&&adv_search=1&page_num=0\thttps://ella.sheba.co.il/חדשות_מכון_אלה
/e/Ella_institute_news/&&adv_search=1&page_num=2\thttps://ella.sheba.co.il/חדשות_מכון_אלה
/e/Medical_Staff/\thttps://eng.sheba.co.il/Ella_medical_staff
/e/Medical_Staff/22.htm\thttps://eng.sheba.co.il/Publication_Prof_Jacob_Schachter
/Links_to_information_sites/\thttps://ella.sheba.co.il/קישורים_לאתרי_מידע
/Research_and_development/Research_Team/31.htm\thttps://www.sheba.co.il/shebaella_Research_Team";
?>