<?php
$redirectText=
"/המחלקה_לניתוחי_לב_שיבא\thttps://heart.sheba.co.il/המחלקה_לניתוחי_לב_שיבא
/היחידה_להשתלות_לב\thttps://heart.sheba.co.il/היחידה_להשתלות_לב
/השתלת_מכשירי_עזר_לחדרי_הלב\thttps://heart.sheba.co.il/השתלת_מכשירי_עזר_לחדרי_הלב
/מצגת_בנושא_השתלות_לב\thttps://heart.sheba.co.il/מצגת_בנושא_השתלות_לב
/חדר_היברידי_במערך_לניתוחי_לב\thttps://heart.sheba.co.il/חדר_היברידי_במערך_לניתוחי_לב
/היחידה_לטיפול_נמרץ_ניתוחי_לב\thttps://heart.sheba.co.il/היחידה_לטיפול_נמרץ_ניתוחי_לב
/חדר_ניתוח_במערך_לניתוחי_לב\thttps://heart.sheba.co.il/חדר_ניתוח_במערך_לניתוחי_לב
/יחידת_הביניים_במערך_לניתוחי_לב\thttps://heart.sheba.co.il/יחידת_הביניים_במערך_לניתוחי_לב
/תחושת_לב_סרט_ניתוחי_לב\thttps://heart.sheba.co.il/המחלקה_לניתוחי_לב_שיבא
/צוות_המערך_לניתוחי_לב\thttps://heart.sheba.co.il/צוות_המערך_לניתוחי_לב
/צוות_רופאים_ניתוחי_לב\thttps://heart.sheba.co.il/צוות_רופאים_ניתוחי_לב
/הצוות_הסיעודי_במערך_לניתוחי_לב\thttps://heart.sheba.co.il/הצוות_הסיעודי_במערך_לניתוחי_לב
/Visiting_Professors\thttps://heart.sheba.co.il/Visiting_Professors
/ניתוחים\thttps://heart.sheba.co.il/ניתוחים
/ניתוח_אבי_העורקים\thttps://heart.sheba.co.il/ניתוח_אבי_העורקים
/ניתוח_בחתך_זעיר_פולשני\thttps://heart.sheba.co.il/ניתוח_בחתך_זעיר_פולשני
/טיפול_כירורגי_בפרפור_פרוזדורים\thttps://heart.sheba.co.il/טיפול_כירורגי_בפרפור_פרוזדורים
/ניתוח_מעקפים\thttps://heart.sheba.co.il/ניתוח_מעקפים
/ניתוח_מסתמים\thttps://heart.sheba.co.il/ניתוח_מסתמים
/מרפאות\thttps://heart.sheba.co.il/מרפאות
/מרפאת_אאורטות\thttps://heart.sheba.co.il/מרפאת_אאורטות
/מרפאת_הוצאת_תפרים\thttps://heart.sheba.co.il/מרפאת_הוצאת_תפרים
/המרכז_לטיפול_בחולי_מרפאן\thttps://heart.sheba.co.il/המרכז_לטיפול_בחולי_מרפאן
/מרפאה_טרום_ניתוחית\thttps://heart.sheba.co.il/מרפאה_טרום_ניתוחית
/מעקב_לאחר_ניתוח\thttps://heart.sheba.co.il/מעקב_לאחר_ניתוח
/מרפאת_פצעים_לאחר_ניתוח_לב\thttps://heart.sheba.co.il/מרפאת_פצעים_לאחר_ניתוח_לב
/תפקיד_העובדת_הסוציאלית_במערך_לניתוחי_לב\thttps://heart.sheba.co.il/תפקיד_העובדת_הסוציאלית_במערך_לניתוחי_לב
";
?>