<?php
$redirectText=
"/News/194.htm\thttps://heart.sheba.co.il/36780
/shilev/\thttps://www.sheba.co.il/מלון_שי_לב
/Research/\thttps://heart.sheba.co.il/מרכז_הלב_מחקרי_לב
/65/\thttps://www.sheba.co.il/shebaheart_old_alias109
/61/\thttps://heart.sheba.co.il/הדרכות_למטופלים_במרכז_הלב
/Arrhythmia_Center/195.htm\thttps://heart.sheba.co.il/מרכז_הלב_הפרעות_קצב_מרפאת_התעלפויות
/89/\thttps://heart.sheba.co.il/מרכז_הלב_מרפאות_הנחיה_תזונתית
/225/\thttps://heart.sheba.co.il/מרכז_הלב_מחקרים_אבחון_בלתי_פולשני_של_מחלת_לב_כלילית
/Arrhythmia_Center/\thttps://heart.sheba.co.il/מרכז_הלב_מרפאות_הפרעות_קצב
/7/\thttps://heart.sheba.co.il/מרכז_הלב_כתבו_לנו
/110/\thttps://heart.sheba.co.il/מרכז_הלב_שיקום_תכנית_ללב_שירות_סוציאלי
/info/\thttps://heart.sheba.co.il/מרכז_הלב_יחידות
/Sheba/About_Heart/\thttps://heart.sheba.co.il/מרכז_הלב_מבנה_הלב_ופעולתו
/Sheba/About_Heart/99.htm\thttps://heart.sheba.co.il/מרכז_הלב_תעוקת_חזה
/Sheba/About_Heart/121.htm\thttps://heart.sheba.co.il/מרכז_הלב_ספריית_מאמרים
/Sheba/About_Heart/126.htm\thttps://heart.sheba.co.il/מרכז_הלב_מאמר_תרופת_הפלא
/Sheba/About_Heart/115.htm\thttps://heart.sheba.co.il/מרכז_הלב_מאמר_טרשת_עורקים
/Sheba/About_Heart/123.htm\thttps://heart.sheba.co.il/מרכז_הלב_שיקום_הלב_ראשי
/192/139.htm\thttps://heart.sheba.co.il/מרכז_הלב_מאמר_כך_תבחר_ארוחה_מתאימה
/Nuclear_Cardiology/\thttps://heart.sheba.co.il/מיפוי_לב
/105/\thttps://heart.sheba.co.il/מרכז_הלב_מחשבון_לב
/Research/Clinical_Trial_Unit/197.htm\thttps://heart.sheba.co.il/מרכז_הלב_מרפאות_הערכת_תפקוד_האנדותל
/101/\thttps://heart.sheba.co.il/מרכז_הלב_שיקום_קבוצת_תמיכה_למטופלי_אי_ספיקת_לב_עם_דפיברילטור
/103/\thttps://heart.sheba.co.il/מרכז_הלב_שיקום_הדרכה_לפני_השתלת_קוצב_דפיבלטור
/Arrhythmia_Center/\thttps://heart.sheba.co.il/מרכז_הלב_מרפאות_הפרעות_קצב
/Sheba/About_Heart/\thttps://heart.sheba.co.il/מרכז_הלב_אודות_הלב
/Units_and_Clinics/\thttps://heart.sheba.co.il/מרכז_הלב_יחידות
/Sheba/About_Heart/95.htm\thttps://heart.sheba.co.il/מרכז_הלב_מבנה_הלב_ופעולתו
/Sheba/About_Heart/99.htm\thttps://heart.sheba.co.il/מרכז_הלב_תעוקת_חזה
/Sheba/About_Heart/98.htm\thttps://heart.sheba.co.il/מרכז_הלב_אוטם_שריר_הלב
/Sheba/information/\thttps://heart.sheba.co.il/מידע-שימושי
/e/Cardiac_Research/\thttps://eng.sheba.co.il/The_Neufeld_Cardiac_Research_Institute
/90/\thttps://heart.sheba.co.il/מרכז_הלב_מרפאת_אי_סי_פי_טי
/Nuclear_Cardiology/\thttps://heart.sheba.co.il/מיפוי_לב
/105/\thttps://heart.sheba.co.il/מרכז_הלב_מחשבון_לב
/Outpatient_clinic/Heart_Failure_clinic/\thttps://heart.sheba.co.il/מרכז_הלב_מרפאות_קרדיומיופתיות_ומחלות_לב_תורשתיות
/Units_and_Clinics/\thttps://heart.sheba.co.il/מרכז_הלב_יחידות
/Sheba/About_Heart/125.htm\thttps://heart.sheba.co.il/מרכז_הלב_מאמר_בשורה_לחולי_תעוקת_חזה
/Sheba/information/37.htm\thttps://heart.sheba.co.il/מרכז_הלב_צרו_קשר
/Sheba/information/\thttps://heart.sheba.co.il/מידע-שימושי
/ICCU/\thttps://heart.sheba.co.il/מרכז_הלב_יחידות_טיפול_נמרץ
/Sheba/About_Us/\thttps://heart.sheba.co.il/מרכז_הלב_ראשי
/Outpatient_clinic/Endothelial_function_clinic/\thttps://heart.sheba.co.il/מרכז_הלב_מרפאות_הערכת_תפקוד_האנדותל
/Sheba/About_Us/184.htm\thttps://www.sheba.co.il/36780
/Rehabilitation/\thttps://heart.sheba.co.il/מרכז_הלב_שיקום_הלב_ראשי
/89/\thttps://heart.sheba.co.il/מרכז_הלב_מרפאות_הנחיה_תזונתית
/Research/Heart_Research_Institute/\thttps://heart.sheba.co.il/מכון_לחקר_הלב
/Sheba/information/176.htm\thttps://heart.sheba.co.il/36588
/Outpatient_clinic/\thttps://heart.sheba.co.il/מרכז_הלב_מרפאות
/Outpatient_clinic/Valve_clinic/\thttps://heart.sheba.co.il/מרכז_הלב_מרפאות_מסתמים
/Cardiac_Catheterization/\thttps://heart.sheba.co.il/36503
/News/219.htm\thttps://www.sheba.co.il/31857
/News/217.htm\thttps://heart.sheba.co.il/31850
/News/227.htm\thttps://heart.sheba.co.il/36811
/Sheba/information/65.htm\thttps://heart.sheba.co.il/מרכז_הלב_מתנדבים_במרכז
/Outpatient_clinic/Valve_clinic/\thttps://heart.sheba.co.il/מרכז_הלב_מרפאות_מסתמים
/e/8/\thttps://www.sheba.co.il/shebaheart_old_alias26
/Outpatient_clinic/Endothelial_function_clinic/\thttps://heart.sheba.co.il/מרכז_הלב_מרפאות_הערכת_תפקוד_האנדותל
/Sheba/About_Heart/107.htm\thttps://heart.sheba.co.il/מרכז_הלב_צנתור_לב
/e/34/\thttps://eng.sheba.co.il/Maintaining_Correct_Eating_Habits
/e/5/\thttps://eng.sheba.co.il/The_Heart_Center_contact_Cardiology_Units
/News/223.htm\thttps://www.sheba.co.il/36808
/e/7/\thttps://eng.sheba.co.il/The_Ultimate_in_twintty_first_Century_Cardiology
/Noninvasive_Cardiology/\thttps://heart.sheba.co.il/מרכז_הלב_יחידות_קרדיולוגיה_לא_פולשנית
/News/223.htm\thttps://heart.sheba.co.il/36808
/News/217.htm\thttps://www.sheba.co.il/31850
/News/220.htm\thttps://heart.sheba.co.il/31861
/News/227.htm\thttps://heart.sheba.co.il/36811
/News/229.htm\thttps://www.sheba.co.il/31915
/e/Cardiac_Research/Clinical_Research_Unit/\thttps://eng.sheba.co.il/Clinical_Research_Unit_Professionalism_Experience
/65/\thttps://heart.sheba.co.il/מרכז_הלב_שיקום_הלב_תוכנית_ללב
/65/132.htm\thttps://heart.sheba.co.il/מרכז_הלב_שיקום_הלב_תוכנית_ללב
/65/130.htm\thttps://heart.sheba.co.il/מרכז_הלב_שיקום_תכנית_ללב_המלצות_תזונתיות
/65/141.htm\thttps://heart.sheba.co.il/מרכז_הלב_שיקום_תכנית_ללב_ביו_פידבק
/65/138.htm\thttps://heart.sheba.co.il/מרכז_הלב_שיקום_תכנית_ללב_פעילות_גופנית_והשפעתה
/Rehabilitation/194.htm\thttps://heart.sheba.co.il/מרכז_הלב_השירות_התזונתי
/Research/Clinical_Trial_Unit/\thttps://heart.sheba.co.il/מרכז_הלב_יחידות_מחקרים_קליניים
/Sheba/About_Heart/95.htm\thttps://heart.sheba.co.il/מרכז_הלב_מבנה_הלב_ופעולתו
/65/146.htm\thttps://heart.sheba.co.il/מרכז_הלב_שיקום_תכנית_ללב_קורס_החייאה_בסיסי
/Cardiology_dept/\thttps://heart.sheba.co.il/מרכז_הלב_יחידות_קרדיולוגיה_ביניים
/News/146.htm\thttps://www.sheba.co.il/31619
/in_the_news/\thttps://heart.sheba.co.il/מרכז_הלב_כתבו_עלינו
/61/\thttps://heart.sheba.co.il/הדרכות_למטופלים_במרכז_הלב
/101/\thttps://heart.sheba.co.il/קבוצת_תמיכה_למטופלי_אי_ספיקת_לב_עם_קוצב_דפיברילטור
/103/\thttps://heart.sheba.co.il/מרכז_הלב_שיקום_הדרכה_לפני_השתלת_קוצב_דפיבלטור
/Outpatient_clinic/Heart_Failure_clinic/\thttps://heart.sheba.co.il/מרכז_הלב_מרפאות_קרדיומיופתיות_ומחלות_לב_תורשתיות
/65/183.htm\thttps://heart.sheba.co.il/מרכז_הלב_שיקום_תכנית_ללב_נזקי_עישון_ושיטות_גמילה
/Cardiac_Catheterization/\thttps://heart.sheba.co.il/36503
/shilev/177.htm\thttps://heart.sheba.co.il/36518
/7/\thttps://heart.sheba.co.il/מרכז_הלב_כתבו_לנו
/Arrhythmia_Center/195.htm\thttps://heart.sheba.co.il/מרכז_הלב_הפרעות_קצב_מרפאת_התעלפויות
/Research/\thttps://heart.sheba.co.il/מרכז_הלב_מחקרי_לב
/News/194.htm\thttps://www.sheba.co.il/36780
/Heart_Failure/\thttps://heart.sheba.co.il/מרכז_הלב_יחידות_אי_ספיקת_לב
/News/229.htm\thttps://www.sheba.co.il/31915
/shilev/\thttps://heart.sheba.co.il/36518
/shilev/177.htm\thttps://heart.sheba.co.il/36518
/Sheba/About_Us/60.htm\thttps://heart.sheba.co.il/מרכז_הלב_התמצאות
/65/133.htm\thttps://heart.sheba.co.il/מרכז_הלב_שיקום_תכנית_ללב_סימנים_תעוקת_חזה_ואוטם_שריר_הלב
/65/137.htm\thttps://heart.sheba.co.il/מרכז_הלב_שיקום_תכנית_ללב_מין_אחרי_אירוע_לב
/Research/Clinical_Trial_Unit/197.htm\thttps://heart.sheba.co.il/מרכז_הלב_מרפאות_הערכת_תפקוד_האנדותל
/News/220.htm\thttps://www.sheba.co.il/31861
/Outpatient_clinic/Heart_Transplant_clinic/\thttps://heart.sheba.co.il/מרכז_הלב_מרפאות_מושתלי_לב
/News/231.htm\thttps://www.sheba.co.il/36813
/Noninvasive_Cardiology/\thttps://heart.sheba.co.il/מרכז_הלב_יחידות_קרדיולוגיה_לא_פולשנית
/Outpatient_clinic/Pregnant_womens_clinic/\thttps://heart.sheba.co.il/מרכז_הלב_מרפאות_הריון_בסיכון_מוגבר
/in_the_news/\thttps://heart.sheba.co.il/מרכז_הלב_כתבו_עלינו
/Sheba/About_Heart/97.htm\thttps://heart.sheba.co.il/מרכז_הלב_הפרעות_קצב
/Sheba/information/144.htm\thttps://heart.sheba.co.il/מרכז_הלב_ספר_הטלפונים
/Outpatient_clinic/Pregnant_womens_clinic/\thttps://heart.sheba.co.il/מרכז_הלב_מרפאות_הריון_בסיכון_מוגבר
/News/219.htm\thttps://www.sheba.co.il/31857
/Sheba/About_Heart/107.htm\thttps://heart.sheba.co.il/מרכז_הלב_צנתור_לב
/News/231.htm\thttps://heart.sheba.co.il/36813
/65/132.htm\thttps://heart.sheba.co.il/מרכז_הלב_שיקום_הלב_תוכנית_ללב
/65/130.htm\thttps://heart.sheba.co.il/מרכז_הלב_שיקום_תכנית_ללב_המלצות_תזונתיות
/65/140.htm\thttps://heart.sheba.co.il/מרכז_הלב_שיקום_תכנית_ללב_הרפיה_ודמיון_מודרך
/65/129.htm\thttps://heart.sheba.co.il/מרכז_הלב_שיקום_תכנית_ללב_טרשת_עורקים
/Rehabilitation/189.htm\thttps://heart.sheba.co.il/מרכז_הלב_שיקום_תכנית_ללב_תפקיד_הטכנאית
/Sheba/information/176.htm\thttps://heart.sheba.co.il/36588
/Heart_Failure/\thttps://heart.sheba.co.il/מרכז_הלב_יחידות_אי_ספיקת_לב
/Sheba/About_Heart/128.htm\thttps://heart.sheba.co.il/מרכז_הלב_מאמר_בדיקה_להערכת_תפקוד_האנדותל
/e/Cardiac_Research/Clinical_Research_Unit/\thttps://eng.sheba.co.il/Clinical_Research_Unit_Professionalism_Experience
/e/34/\thttps://eng.sheba.co.il/Maintaining_Correct_Eating_Habits
/News/\thttps://heart.sheba.co.il/מרכז_הלב_ארכיון_חדשות
/News/&&adv_search=1\thttps://heart.sheba.co.il/מרכז_הלב_ארכיון_חדשות
/News/&adv_search=1&page_num=6\thttps://heart.sheba.co.il/מרכז_הלב_ארכיון_חדשות
/News/&adv_search=1&page_num=7\thttps://heart.sheba.co.il/מרכז_הלב_ארכיון_חדשות
/News/&adv_search=1&page_num=3\thttps://heart.sheba.co.il/מרכז_הלב_ארכיון_חדשות
/News/&adv_search=1&page_num=2\thttps://heart.sheba.co.il/מרכז_הלב_ארכיון_חדשות
/News/&adv_search=1&page_num=5\thttps://heart.sheba.co.il/מרכז_הלב_ארכיון_חדשות
/News/&adv_search=1&page_num=4\thttps://heart.sheba.co.il/מרכז_הלב_ארכיון_חדשות
/News/&adv_search=1&page_num=1\thttps://heart.sheba.co.il/מרכז_הלב_ארכיון_חדשות
/News/&adv_search=1&page_num=0\thttps://heart.sheba.co.il/מרכז_הלב_ארכיון_חדשות
/News/146.htm\thttps://www.sheba.co.il/31619
/225/\thttps://heart.sheba.co.il/מרכז_הלב_מחקרים_אבחון_בלתי_פולשני_של_מחלת_לב_כלילית
/110/\thttps://heart.sheba.co.il/מרכז_הלב_שיקום_תכנית_ללב_שירות_סוציאלי
/65/137.htm\thttps://heart.sheba.co.il/מרכז_הלב_שיקום_תכנית_ללב_מין_אחרי_אירוע_לב
/65/146.htm\thttps://heart.sheba.co.il/מרכז_הלב_שיקום_תכנית_ללב_קורס_החייאה_בסיסי
/News/&&adv_search=1&page_num=4\thttps://heart.sheba.co.il/מרכז_הלב_ארכיון_חדשות
/News/&&adv_search=1&page_num=5\thttps://heart.sheba.co.il/מרכז_הלב_ארכיון_חדשות
/News/&&adv_search=1&page_num=2\thttps://heart.sheba.co.il/מרכז_הלב_ארכיון_חדשות
/News/&&adv_search=1&page_num=3\thttps://heart.sheba.co.il/מרכז_הלב_ארכיון_חדשות
/News/&&adv_search=1&page_num=6\thttps://heart.sheba.co.il/מרכז_הלב_ארכיון_חדשות
/News/&&adv_search=1&page_num=7\thttps://heart.sheba.co.il/מרכז_הלב_ארכיון_חדשות
/News/&&adv_search=1&page_num=1\thttps://heart.sheba.co.il/מרכז_הלב_ארכיון_חדשות
/News/&&adv_search=1&page_num=0\thttps://heart.sheba.co.il/מרכז_הלב_ארכיון_חדשות
/in_the_news/186.htm\thttps://www.sheba.co.il/shebaheart_in_the_news
/News/&page_num=2\thttps://heart.sheba.co.il/מרכז_הלב_ארכיון_חדשות
/News/&page_num=3\thttps://heart.sheba.co.il/מרכז_הלב_ארכיון_חדשות
/News/&page_num=4\thttps://heart.sheba.co.il/מרכז_הלב_ארכיון_חדשות
/News/&page_num=5\thttps://heart.sheba.co.il/מרכז_הלב_ארכיון_חדשות
/News/&page_num=6\thttps://heart.sheba.co.il/מרכז_הלב_ארכיון_חדשות
/News/&page_num=7\thttps://heart.sheba.co.il/מרכז_הלב_ארכיון_חדשות
/News/&page_num=0\thttps://heart.sheba.co.il/מרכז_הלב_ארכיון_חדשות
/News/&page_num=1\thttps://heart.sheba.co.il/מרכז_הלב_ארכיון_חדשות
/shilev/&SearchClean=1\thttps://www.sheba.co.il/מלון_שי_לב
/Sheba/About_Heart/97.htm\thttps://heart.sheba.co.il/מרכז_הלב_הפרעות_קצב
/in_the_news/186.htm\thttps://www.sheba.co.il/shebaheart_in_the_news
/65/141.htm\thttps://heart.sheba.co.il/מרכז_הלב_שיקום_תכנית_ללב_ביו_פידבק
/e/Cardiac_Research/\thttps://eng.sheba.co.il/The_Neufeld_Cardiac_Research_Institute
/e/8/\thttps://www.sheba.co.il/shebaheart_old_alias26
/Sheba/information/144.htm\thttps://heart.sheba.co.il/מרכז_הלב_ספר_הטלפונים
/e/7/\thttps://eng.sheba.co.il/The_Ultimate_in_twintty_first_Century_Cardiology
/e/5/\thttps://eng.sheba.co.il/The_Heart_Center_contact_Cardiology_Units
/65/133.htm\thttps://heart.sheba.co.il/מרכז_הלב_שיקום_תכנית_ללב_סימנים_תעוקת_חזה_ואוטם_שריר_הלב
/61/62.htm\thttps://heart.sheba.co.il/הדרכות_למטופלים_במרכז_הלב
/99/\thttps://heart.sheba.co.il/הדרכת_מטופלים_לאחר_השתלת_לב
/Sheba/About_Us/60.htm\thttps://heart.sheba.co.il/מרכז_הלב_התמצאות
/Sheba/information/65.htm\thttps://heart.sheba.co.il/מרכז_הלב_מתנדבים_במרכז
/98/\thttps://heart.sheba.co.il/מרכז_הלב_שיקום_הדרכה_לאחר_אוטם_או_צנתור
/65/140.htm\thttps://heart.sheba.co.il/מרכז_הלב_שיקום_תכנית_ללב_הרפיה_ודמיון_מודרך
/Sheba/About_Heart/98.htm\thttps://heart.sheba.co.il/מרכז_הלב_אוטם_שריר_הלב
/65/183.htm\thttps://heart.sheba.co.il/מרכז_הלב_שיקום_תכנית_ללב_נזקי_עישון_ושיטות_גמילה
/News/\thttps://heart.sheba.co.il/מרכז_הלב_ארכיון_חדשות
/News/&&adv_search=1\thttps://heart.sheba.co.il/מרכז_הלב_ארכיון_חדשות
/News/&page_num=6\thttps://heart.sheba.co.il/מרכז_הלב_ארכיון_חדשות
/News/&page_num=5\thttps://heart.sheba.co.il/מרכז_הלב_ארכיון_חדשות
/News/&&adv_search=1&page_num=1\thttps://heart.sheba.co.il/מרכז_הלב_ארכיון_חדשות
/News/&page_num=3\thttps://heart.sheba.co.il/מרכז_הלב_ארכיון_חדשות
/News/&page_num=4\thttps://heart.sheba.co.il/מרכז_הלב_ארכיון_חדשות
/News/&page_num=7\thttps://heart.sheba.co.il/מרכז_הלב_ארכיון_חדשות
/News/&&adv_search=1&page_num=2\thttps://heart.sheba.co.il/מרכז_הלב_ארכיון_חדשות
/News/&&adv_search=1&page_num=0\thttps://heart.sheba.co.il/מרכז_הלב_ארכיון_חדשות
/News/&page_num=1\thttps://heart.sheba.co.il/מרכז_הלב_ארכיון_חדשות
/News/&page_num=2\thttps://heart.sheba.co.il/מרכז_הלב_ארכיון_חדשות
/News/&&adv_search=1&page_num=3\thttps://heart.sheba.co.il/מרכז_הלב_ארכיון_חדשות
/News/&page_num=0\thttps://heart.sheba.co.il/מרכז_הלב_ארכיון_חדשות
/News/&&adv_search=1&page_num=4\thttps://heart.sheba.co.il/מרכז_הלב_ארכיון_חדשות
/News/&&adv_search=1&page_num=5\thttps://heart.sheba.co.il/מרכז_הלב_ארכיון_חדשות
/News/&&adv_search=1&page_num=6\thttps://heart.sheba.co.il/מרכז_הלב_ארכיון_חדשות
/News/&&adv_search=1&page_num=7\thttps://heart.sheba.co.il/מרכז_הלב_ארכיון_חדשות
/90/\thttps://heart.sheba.co.il/מרכז_הלב_מרפאת_אי_סי_פי_טי
/Outpatient_clinic/Heart_Transplant_clinic/\thttps://heart.sheba.co.il/מרכז_הלב_מרפאות_מושתלי_לב
/Sheba/About_Us/184.htm\thttps://www.sheba.co.il/36780
/Cardiology_dept/\thttps://heart.sheba.co.il/מרכז_הלב_יחידות_קרדיולוגיה_ביניים
/99/\thttps://heart.sheba.co.il/הדרכת_מטופלים_לאחר_השתלת_לב
/98/\thttps://heart.sheba.co.il/מרכז_הלב_שיקום_הדרכה_לאחר_אוטם_או_צנתור
/Research/Heart_Research_Institute/\thttps://heart.sheba.co.il/מרכז_הלב_שיקום_הלב_ראשי
/Sheba/About_Heart/121.htm\thttps://heart.sheba.co.il/מרכז_הלב_ספריית_מאמרים
/Sheba/About_Heart/128.htm\thttps://heart.sheba.co.il/מרכז_הלב_מאמר_בדיקה_להערכת_תפקוד_האנדותל
/192/139.htm\thttps://heart.sheba.co.il/מרכז_הלב_מאמר_כך_תבחר_ארוחה_מתאימה
/Sheba/About_Heart/125.htm\thttps://heart.sheba.co.il/מרכז_הלב_מאמר_בשורה_לחולי_תעוקת_חזה
/Sheba/About_Heart/136.htm\thttps://heart.sheba.co.il/מרכז_הלב_מאמר_הטוב_הרע_והמטרה
/Rehabilitation/193.htm\thttps://heart.sheba.co.il/מרכז_הלב_השירות_הפסיכולוגי
/105/&go_form=1\thttps://heart.sheba.co.il/מרכז_הלב_מחשבון_לב
/News/&adv_search=1&page_num=7\thttps://heart.sheba.co.il/מרכז_הלב_ארכיון_חדשות
/News/&adv_search=1&page_num=5\thttps://heart.sheba.co.il/מרכז_הלב_ארכיון_חדשות
/News/&adv_search=1&page_num=6\thttps://heart.sheba.co.il/מרכז_הלב_ארכיון_חדשות
/News/&adv_search=1&page_num=0\thttps://heart.sheba.co.il/מרכז_הלב_ארכיון_חדשות
/News/&adv_search=1&page_num=3\thttps://heart.sheba.co.il/מרכז_הלב_ארכיון_חדשות
/News/&adv_search=1&page_num=4\thttps://heart.sheba.co.il/מרכז_הלב_ארכיון_חדשות
/News/&adv_search=1&page_num=2\thttps://heart.sheba.co.il/מרכז_הלב_ארכיון_חדשות
/News/&adv_search=1&page_num=1\thttps://heart.sheba.co.il/מרכז_הלב_ארכיון_חדשות
/Sheba/About_Heart/126.htm\thttps://heart.sheba.co.il/מרכז_הלב_מאמר_תרופת_הפלא
/Sheba/About_Heart/123.htm\thttps://heart.sheba.co.il/מרכז_הלב_שיקום_הלב_ראשי
/Sheba/About_Heart/136.htm\thttps://heart.sheba.co.il/מרכז_הלב_מאמר_הטוב_הרע_והמטרה
/Outpatient_clinic/Young_at_risk_patient_clinic/\thttps://heart.sheba.co.il/מרכז_הלב_מרפאות_צעירים
/65/129.htm\thttps://heart.sheba.co.il/מרכז_הלב_שיקום_תכנית_ללב_טרשת_עורקים
/Sheba/About_Heart/180.htm\thttps://heart.sheba.co.il/מרכז_הלב_מאמר_פרפור_פרוזדורים
/Outpatient_clinic/Young_at_risk_patient_clinic/\thttps://heart.sheba.co.il/מרכז_הלב_מרפאות_צעירים
/Rehabilitation/\thttps://heart.sheba.co.il/מרכז_הלב_שיקום_הלב_ראשי
/Rehabilitation/193.htm\thttps://heart.sheba.co.il/מרכז_הלב_השירות_הפסיכולוגי
/Rehabilitation/194.htm\thttps://heart.sheba.co.il/מרכז_הלב_השירות_התזונתי
/Rehabilitation/189.htm\thttps://heart.sheba.co.il/מרכז_הלב_שיקום_תכנית_ללב_תפקיד_הטכנאית
/Research/Clinical_Trial_Unit/\thttps://heart.sheba.co.il/מרכז_הלב_יחידות_מחקרים_קליניים
/Sheba/About_Heart/180.htm\thttps://heart.sheba.co.il/מרכז_הלב_מאמר_פרפור_פרוזדורים
/65/138.htm\thttps://heart.sheba.co.il/מרכז_הלב_שיקום_תכנית_ללב_פעילות_גופנית_והשפעתה";
?>